### ISSUE TITLE
Improve low-level TCP connection interface

### ISSUE THREAD

**Issue by eklitzke** [skypjack/uvw#102]
I have an application that needs to do the following:
 * Resolve a DNS name
 * Try to connect to all the resolved addresses (until one succeeds)

This is currently difficult to do with the API exposed by uvw. The DNS interface is just fine, but I think the TCP connect methods need some work. Specifically, the TCP::connect methods take a string name, and only connect to the first resolved name.

Right now I've just kind of copied the logic from TCP::connect in my own application, which works but is kind of ugly (in my opinion). A cleaner way to do this would be to add a new TCP::connect overloaded method that accepts a pointer/reference to a struct addrinfo.

**Comment by skypjack** [comment]
I'm out of home until Sunday. I'll look into the issue next week probably.  
I'm sorry for the inconvenience.

**Comment by skypjack** [comment]
Let me know if it works for you. It's on branch `wip`.  
If it's fine, I can merge it on `master` and close the issue.

**Comment by skypjack** [comment]
[Available on `master`](https://github.com/skypjack/uvw/blob/master/src/uvw/tcp.hpp#L208).
