### ISSUE TITLE
build error with vs2017

### ISSUE THREAD

**Issue by Lance0724** [skypjack/uvw#108]
1>uvw\stream.hpp(162): error C2061: syntax error: identifier 'ConstructorAccess'
1>uvw\stream.hpp(448): note: see reference to class template instantiation 'uvw::StreamHandle<T,U>' being compiled
1>uvw\resource.hpp(19): note: see reference to class template instantiation 'uvw::UnderlyingType<T,U>' being compiled
......................

The same source code can build successful with vs2015

**Comment by skypjack** [comment]
Have you tried to fix it and can already propose a solution?
I don't have VS2017 on board. Probably I can arrange something using appveyor but it will take a while for my free time isn't properly _free_ currently.

**Comment by Lance0724** [comment]
I have tried to fix. But I did not find the reason  abort the build error.

**Comment by skypjack** [comment]
I tried using VS2017 on appveyor (see branch `vs2017`) and [it works fine](https://ci.appveyor.com/project/skypjack/uvw).
Tests compiles with no errors, also those that involve a `StreamHandle`

>The same source code can build successful with vs2015

Are you experiencing the problem while compiling the tests or whatever?
If not, please provide a minimal example to reproduce the error. Otherwise I must think it's in the client code and close the issue.
There are not enough information so far to be able to help you.

**Comment by Lance0724** [comment]
I just use  the "Code Example" in the github uvw README.md. 
Just include header and libuv.lib without any change.

I think maybe it is a bug of c++11/14 compatibility  in vs2017(V141)  Platform Toolset. 

Anyway, very thank you for your help.

**Comment by skypjack** [comment]
You're welcome.

**Comment by ardanew** [comment]
1. make /permissive+ flag in visual studio 2017
OR
2. change source to something like
`
#ifdef _MSC_VER
 	using ConstructorAccess = Handle<T, U>::ConstructorAccess;
     StreamHandle(ConstructorAccess ca, std::shared_ptr<Loop> ref)
         : Handle<T, U>{ca, std::move(ref)}
     {}
#else
`

**Comment by Jasper0819X** [comment]
same problem when using vs2017 15.8.6.
change stream.hpp line 162 from:
```cpp
#ifdef _MSC_VER
StreamHandle(ConstructorAccess ca, std::shared_ptr<Loop> ref)
        : Handle{ca, std::move(ref)}
    {}
#else
    using Handle<T, U>::Handle;
#endif

```
 to:
```cpp
#ifdef _MSC_VER
StreamHandle(typename Handle<T, U>::ConstructorAccess ca, std::shared_ptr<Loop> ref)
        : Handle<T, U>{ca, std::move(ref)}
    {}
#else
    using Handle<T, U>::Handle;
#endif
```

**Comment by skypjack** [comment]
@Jasper0819X would you open a PR?

**Comment by Jasper0819X** [comment]
@skypjack see PR #134. Tested on vs2017 with toolchain v140(vs2015) and v141(vs2017)
