### ISSUE TITLE
Help wanted: libuv v2 is almost ready to release

### ISSUE THREAD

**Issue by skypjack** [skypjack/uvw#111]
It seems that `libuv` v2 [is almost ready](https://github.com/libuv/libuv/issues/1597#issuecomment-368048251) and it will be _released_ on March (at least part of it).  
`uvw` requires probably a good amount of work to support it and currently I've not much free time to work on this project. Moreover, I'm no longer using the library actively on any project, so I won't work on this during the day.

Unless either some volunteers show up here or someone is willing to consider funded development (contact me privately in this case), `uvw` will be discontinued or put under dual license if I find the time to work on `uvw` v2.

---

I'll close this issue in a couple of weeks.

**Comment by skypjack** [comment]
So far, so good. It looks like nobody is interested in the project, so... Time to close the issue.

**Comment by abrownsword** [comment]
Unfortunately I wasn’t watching when you were asking this question.  Is there a link to the scope of v2 changes?  I don’t see very much on the github libuv repo.

**Comment by skypjack** [comment]
@abrownsword I suspect the only way to know what will be in libuv v2 is through the issues tagged v2.

**Comment by skypjack** [comment]
It isn't. It's just a matter of time. :-)
I'll work on it as soon as they release v2 and let's see how long it takes.
