### ISSUE TITLE
Building problems in Ubuntu 16.04 Server Edition 

### ISSUE THREAD

**Issue by marcoippolito** [skypjack/uvw#118]
`marco@PC:~$ cd uvw/
    marco@PC:~/uvw$ cd build/
    marco@PC:~/uvw/build$ cmake ..
    -- The C compiler identification is GNU 8.1.0
    -- The CXX compiler identification is GNU 8.1.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    *
    * uvw v1.10.0 (Debug)
    * Copyright (c) 2018 Michele Caini <michele.caini@gmail.com>
    *
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Check if compiler accepts -pthread
    -- Check if compiler accepts -pthread - yes
    -- Found Threads: TRUE
    -- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) (Required is at least version "1.8")
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/marco/uvw/deps/googletest
    Scanning dependencies of target googletest
    [ 11%] Creating directories for 'googletest'
    [ 22%] Performing download step (git clone) for 'googletest'
    Cloning into 'src'...
    Already on 'master'
    Your branch is up-to-date with 'origin/master'.
    [ 33%] No patch step for 'googletest'
    [ 44%] Performing update step for 'googletest'
    Current branch master is up to date.
    [ 55%] No configure step for 'googletest'
    [ 66%] No build step for 'googletest'
    [ 77%] No install step for 'googletest'
    [ 88%] No test step for 'googletest'
    [100%] Completed 'googletest'
    [100%] Built target googletest
    -- Found PythonInterp: /usr/bin/python (found version "2.7.12")
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/marco/uvw/deps/libuv
    Scanning dependencies of target libuv
    [ 11%] Creating directories for 'libuv'
    [ 22%] Performing download step (git clone) for 'libuv'
    Cloning into 'src'...
    Note: checking out 'v1.21.0'.

    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.

    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:
 
      git checkout -b <new-branch-name>
 
    HEAD is now at e4983a9... 2018.06.23, Version 1.21.0 (Stable)
    [ 33%] No patch step for 'libuv'
    [ 44%] Performing update step for 'libuv'
    [ 55%] Performing configure step for 'libuv'
    /home/marco/uvw/deps/libuv/src/autogen.sh: 1: /home/marco/uvw/deps/libuv/src/autogen.sh:   
    automake: not found
    /home/marco/uvw/deps/libuv/src/autogen.sh: 33: test: Illegal number:
    /home/marco/uvw/deps/libuv/src/autogen.sh: 34: test: Illegal number:
    + libtoolize --copy
    /home/marco/uvw/deps/libuv/src/autogen.sh: 43: /home/marco/uvw/deps/libuv/src/autogen.sh:   
    libtoolize: not found
    CMakeFiles/libuv.dir/build.make:106: recipe for target 'stamp/libuv-configure' failed
    make[2]: *** [stamp/libuv-configure] Error 127
    CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/libuv.dir/all' failed
    make[1]: *** [CMakeFiles/libuv.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2
    CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    libuv_static
        linked by target "util" in directory /home/marco/uvw/test
        linked by target "work" in directory /home/marco/uvw/test
        linked by target "fs_req" in directory /home/marco/uvw/test
        linked by target "udp" in directory /home/marco/uvw/test
        linked by target "handle" in directory /home/marco/uvw/test
        linked by target "fs_event" in directory /home/marco/uvw/test
        linked by target "thread" in directory /home/marco/uvw/test
        linked by target "fs_poll" in directory /home/marco/uvw/test
        linked by target "main" in directory /home/marco/uvw/test
        linked by target "loop" in directory /home/marco/uvw/test
        linked by target "file_req" in directory /home/marco/uvw/test
        linked by target "idle" in directory /home/marco/uvw/test
        linked by target "emitter" in directory /home/marco/uvw/test
        linked by target "async" in directory /home/marco/uvw/test
        linked by target "dns" in directory /home/marco/uvw/test
        linked by target "prepare" in directory /home/marco/uvw/test
        linked by target "lib" in directory /home/marco/uvw/test
        linked by target "process" in directory /home/marco/uvw/test
        linked by target "check" in directory /home/marco/uvw/test
        linked by target "resource" in directory /home/marco/uvw/test
        linked by target "signal" in directory /home/marco/uvw/test
        linked by target "poll" in directory /home/marco/uvw/test
        linked by target "stream" in directory /home/marco/uvw/test
        linked by target "tcp" in directory /home/marco/uvw/test
        linked by target "request" in directory /home/marco/uvw/test
        linked by target "timer" in directory /home/marco/uvw/test
        linked by target "tty" in directory /home/marco/uvw/test
        linked by target "underlying_type" in directory /home/marco/uvw/test
        linked by target "pipe" in directory /home/marco/uvw/test

    -- Configuring incomplete, errors occurred!
    See also "/home/marco/uvw/build/CMakeFiles/CMakeOutput.log".
    See also "/home/marco/uvw/build/CMakeFiles/CMakeError.log".
    marco@PC:~/uvw/build$
    `
What to do to solve the problem?
Marco

**Comment by skypjack** [comment]
The problem arises when you try to compile `libuv`:

>/home/marco/uvw/deps/libuv/src/autogen.sh: 1: /home/marco/uvw/deps/libuv/src/autogen.sh:   
>automake: not found

It looks like you have to install `automake` on your system. :smile: 
Try to do it and to compile the tests. Let's see if it works or if you get a different error at least.

**Comment by marcoippolito** [comment]
After automake installation and check:

    `marco@PC:~/uvw/build$ sudo apt-get install automake
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    automake is already the newest version (1:1.15-4ubuntu1).
    0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.
    `
and after doxygen installation and check:

    `marco@PC:~$ sudo apt-get install doxygen
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    doxygen is already the newest version (1.8.11-1).
    0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.
    `

    `marco@PC:~$ rm -rf uvw
    marco@PC:~$ git clone https://github.com/skypjack/uvw.git
    marco@PC:~$ git clone https://github.com/skypjack/uvw.git
    Cloning into 'uvw'...
    remote: Counting objects: 6322, done.
    remote: Compressing objects: 100% (173/173), done.
    remote: Total 6322 (delta 420), reused 299 (delta 285), pack-reused 5862
    Receiving objects: 100% (6322/6322), 4.04 MiB | 2.77 MiB/s, done.
    Resolving deltas: 100% (4512/4512), done.
    Checking connectivity... done.
    marco@PC:~$ cd uvw/
    marco@PC:~/uvw$ cd build/
    marco@PC:~/uvw/build$ cmake ..
    -- The C compiler identification is GNU 8.1.0
    -- The CXX compiler identification is GNU 8.1.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    *
    * uvw v1.10.0 (Debug)
    *Copyright (c) 2018 Michele Caini <michele.caini@gmail.com>
    *
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Check if compiler accepts -pthread
    -- Check if compiler accepts -pthread - yes
    -- Found Threads: TRUE
    -- Found Doxygen: /usr/bin/doxygen (found suitable version "1.8.11", minimum required is "1.8")
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/marco/uvw/deps/googletest
    Scanning dependencies of target googletest
    [ 11%] Creating directories for 'googletest'
    [ 22%] Performing download step (git clone) for 'googletest'
    Cloning into 'src'...
    Already on 'master'
   Your branch is up-to-date with 'origin/master'.
    [ 33%] No patch step for 'googletest'
    [ 44%] Performing update step for 'googletest'
    Current branch master is up to date.
    [ 55%] No configure step for 'googletest'
    [ 66%] No build step for 'googletest'
    [ 77%] No install step for 'googletest'
    [ 88%] No test step for 'googletest'
    [100%] Completed 'googletest'
    [100%] Built target googletest
    -- Found PythonInterp: /usr/bin/python (found version "2.7.12")
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/marco/uvw/deps/libuv
    Scanning dependencies of target libuv
    [ 11%] Creating directories for 'libuv'
    [ 22%] Performing download step (git clone) for 'libuv'
    Cloning into 'src'...
    Note: checking out 'v1.21.0'.

    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.

    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:

      git checkout -b <new-branch-name>

    HEAD is now at e4983a9... 2018.06.23, Version 1.21.0 (Stable)
    [ 33%] No patch step for 'libuv'
    [ 44%] Performing update step for 'libuv'
    [ 55%] Performing configure step for 'libuv'
    + libtoolize --copy
    /home/marco/uvw/deps/libuv/src/autogen.sh: 43: /home/marco/uvw/deps/libuv/src/autogen.sh:  
    libtoolize: not found
    CMakeFiles/libuv.dir/build.make:106: recipe for target 'stamp/libuv-configure' failed
    make[2]: *** [stamp/libuv-configure] Error 127
    CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/libuv.dir/all' failed
    make[1]: *** [CMakeFiles/libuv.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2
    CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    libuv_static
        linked by target "util" in directory /home/marco/uvw/test
        linked by target "work" in directory /home/marco/uvw/test
        linked by target "fs_req" in directory /home/marco/uvw/test
        linked by target "udp" in directory /home/marco/uvw/test
        linked by target "handle" in directory /home/marco/uvw/test
        linked by target "fs_event" in directory /home/marco/uvw/test
        linked by target "thread" in directory /home/marco/uvw/test
        linked by target "fs_poll" in directory /home/marco/uvw/test
        linked by target "main" in directory /home/marco/uvw/test
        linked by target "loop" in directory /home/marco/uvw/test
        linked by target "file_req" in directory /home/marco/uvw/test
        linked by target "idle" in directory /home/marco/uvw/test
        linked by target "emitter" in directory /home/marco/uvw/test
        linked by target "async" in directory /home/marco/uvw/test
        linked by target "dns" in directory /home/marco/uvw/test
        linked by target "prepare" in directory /home/marco/uvw/test
        linked by target "lib" in directory /home/marco/uvw/test
        linked by target "process" in directory /home/marco/uvw/test
        linked by target "check" in directory /home/marco/uvw/test
        linked by target "resource" in directory /home/marco/uvw/test
        linked by target "signal" in directory /home/marco/uvw/test
        linked by target "poll" in directory /home/marco/uvw/test
        linked by target "stream" in directory /home/marco/uvw/test
        linked by target "tcp" in directory /home/marco/uvw/test
        linked by target "request" in directory /home/marco/uvw/test
        linked by target "timer" in directory /home/marco/uvw/test
         linked by target "tty" in directory /home/marco/uvw/test
        linked by target "underlying_type" in directory /home/marco/uvw/test
        linked by target "pipe" in directory /home/marco/uvw/test

    -- Configuring incomplete, errors occurred!
    See also "/home/marco/uvw/build/CMakeFiles/CMakeOutput.log".
    See also "/home/marco/uvw/build/CMakeFiles/CMakeError.log".
    `

**Comment by skypjack** [comment]
Another error, another tool to install:

>/home/marco/uvw/deps/libuv/src/autogen.sh: 43: /home/marco/uvw/deps/libuv/src/autogen.sh:  
>libtoolize: not found

Have a go installing `libtoolize`. Btw these are problems you're encountering while you try to compile `libuv`, `uvw` has nothing to do with them. I mean, if you try to clone `libuv` and to compile it, it will fail as well with the same errors.

**Comment by marcoippolito** [comment]
`marco@PC:~$ sudo apt-get install libtoolize
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    E: Unable to locate package libtoolize
    `

Before trying today again to build uvw I installed via git clone and successfully tested with Cmake libuv

**Comment by skypjack** [comment]
Yeah, the _cmake-way_ doesn't require these tools. They are all about the _autotool-way_.   Unfortunately, when I started working `uvw`, `libuv` didn't support cmake yet.  
Currently I'm not actively working on the project. I'm just maintaining it in the free time. Because of this, please, didn't expect to see `uvw` switching to cmake any time soon.

That being said, the package to install is `libtool`. `libtoolize` is part of it. Try this:
```
sudo apt-get install libtool
```
Let me know if it works. :wink:

**Comment by marcoippolito** [comment]
Building and testing phases gone fine. 
Thanks

**Comment by skypjack** [comment]
You're welcome!! :wink:
