### ISSUE TITLE
vectorised writes on uv_stream_t handles

### ISSUE THREAD

**Issue by byteystring** [skypjack/uvw#122]
Hi,

I was looking through the documentation, and it seems that uvw does not expose a way to write multiple buffers in one uv_write. While I could use the raw handle and circumvent uvw, I am left wondering why this is the case and if you would introduce support for vectorised writes in the future.

**Comment by skypjack** [comment]
I confirm that `uvw` doesn't expose a way to write multiple buffers at once. To be honest, it would be quite easy to add it, but I've not enough bandwidth to work on the project for free right now.

Currently `uvw` is in a sort of  _maintenance mode_ until I find some spare time to spend on it or someone willing to fund the development of new features. In the meantime, I'll keep it in sync with `libuv` as long as I can, but I won't work on new functionalities, I'm sorry.

However, if you want to try and pack a PR, I'd be glad to review it.

**Comment by skypjack** [comment]
I see that you aren't interested in contributing to the library, so we can close the issue as _wontfix_. I'm still available to review a PR in future if you want to participate. Thank you.

**Comment by byteystring** [comment]
Apologies, I have been really busy the past week. I currently don't have
cycles to spend contributing to the project, and I implemented a temporary
workaround in my project that uses the raw uv_handle and the C API.

When I get some free time I will try and contribute an implementation
because I think it would be a useful feature to have for several workload
types.

**Comment by skypjack** [comment]
Thank you. It would be great to see other users contributing to the project because I'm short in free time to be able to work on it alone.
