### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by skypjack** [skypjack/uvw#126]
Hi all,

I just realized that we don't have a logo for uvw yet. :-)
It would be great if someone wanted to suggest something or make a contribution directly with an image.
Thank you very much for your help!!

**Comment by richardbmx** [comment]
I'm going to work on adding the V to this ;-)

![logo104](https://user-images.githubusercontent.com/35604837/45586727-f13c5380-b8c9-11e8-910b-f04d8985ea42.png)

**Comment by refack** [comment]
I love our Unicorn Velociraptor
https://github.com/libuv/libuv/blob/v1.x/img/logos.svg
Maybe add **W**ings to it.

**Comment by richardbmx** [comment]
I present this second model where the two letters are incorporated in a single silhouette which makes it a personalized and unique icon for your project.

![logo1042](https://user-images.githubusercontent.com/35604837/45587430-5183c300-b8d3-11e8-8a60-bd1d7ee60730.png)

**Comment by skypjack** [comment]
Onestamente no

**Comment by richardbmx** [comment]
@skypjack  the better time for being simpler a simple logo is kinder to see integrate the V gives sierta pesades to the design that makes it look loaded however try to be as simple as possible. The white U inside the black box is simply a favicon version of the entire base design, you can see how it works very well in different versions, for being a simple and friendly design.

**Comment by refack** [comment]
this![image](https://user-images.githubusercontent.com/96947/45590699-5dd84200-b90c-11e8-8b05-c29bcfb95ca3.png)?

Probably my fav of the day as well.
I would sleep on it, see if you still like it tomorrow.

**Comment by refack** [comment]
P.S. @richardbmx, you rock!

**Comment by richardbmx** [comment]
@refack that is the black version of the full color logo, however, if you want it, you can also use it

**Comment by richardbmx** [comment]
@skypjack  perfect I hope confirmation to send you all the files... and thank you very much for the trust ;-)

**Comment by refack** [comment]
Hello to you two 🎩 
I'm a `libuv` collaborator (and Node.js), but I'm on a modern C++ kick so obviously I thought about a C++20 wrapper for uv, and wise wise Google brought me here.

BTW: I'm gonna try and push this into Node.js, right after I land the GSL in, and get consensus on adopting the C++CG.

**Comment by skypjack** [comment]
Sorry if I'm late, I've been busy last week.
@richardbmx I'd go with your first proposal, I like it. What are the next steps?

**Comment by richardbmx** [comment]
@skypjack  Now I will generate the folder with all the files and I will send you the link sharing the folder so you can use the logo

**Comment by skypjack** [comment]
@richardbmx Fine for me. Let me know also what can I do for you. If I remember it correctly, a line in the contributors list and a mention in the README file, right?

**Comment by richardbmx** [comment]
@skypjack I share the folder with all the necessary files to use the logo, all are in 100% editable format and vector format, inside the folder there is a copyright document which gives you freedom to use the logo. if you need something else you should just ask for it.

;-) greetings 

[Google Drive](https://drive.google.com/open?id=19lxdE_oghtegjTxZn1n5g8fVXA0TNiu0)

**Comment by skypjack** [comment]
@richardbmx Thank you very much!! I added the logo to the project on branch `experimental`. I'm going to merge it on `master` in a while.  
I added your name to the README file and a link to the license as required by the CC BY-SA 4.0. Moreover, I added your name and GitHub user to the contributor list.

I'm closing the issue. Feel free to drop a comment anyway if you want/need.

**Comment by richardbmx** [comment]
@skypjack Perfect looks the logo very well, I hope to contribute in future projects greetings ..

**Comment by refack** [comment]
> > I'm gonna try and push this into Node.js
> 
> @refack _This_ what? I never thought anyone would ever dare so much. Count me on if you need help.

Yes, having UVW as a way to use UV.
It probably will be an uphill battle, but if I show a net positive effect on code quality without performance penalty, it will be possible.

**Comment by skypjack** [comment]
@refack It sounds good. Let me know how can help you climbing up.
