### ISSUE TITLE
uvw::ProcessHandle blocks user-supplied stream as stdin

### ISSUE THREAD

**Issue by zxtwonder** [skypjack/uvw#128]
Thank you for the excellent library!

We encountered an interesting issue with uvw::ProcessHandle's constructor, which always adds stdin as a fd.
https://github.com/skypjack/uvw/blob/e89da652409d20bdd00b2db2d632f300d21baa7b/src/uvw/process.hpp#L79
It prevents using uvw::StreamHandle for stdin since entries in poFdStdio are placed before those in poStreamStdio.

Was there some reason to always initialize stdin as a fd? Without this special treatment of stdin, logic in
```
ProcessHandle & stdio(FileHandle fd, Flags<StdIO> flags)
```
can also be simplified.

Thanks

**Comment by skypjack** [comment]
Probably I went way too strict in interpreting [this](http://docs.libuv.org/en/v1.x/process.html#uv_process_option_t.stdio) (emphasis mine):

>**uv_process_options_t.stdio**
>The stdio field points to an array of uv_stdio_container_t structs that describe the file descriptors that will be made available to the child process. **The convention is that stdio[0] points to stdin**, fd 1 is used for stdout, and fd 2 is stderr.

Not even sure about it, because that part of the documentation is quite obscure to me.  
If you have experience with `libuv`, feel free to provide me with all the details and let's discuss it.

**Comment by zxtwonder** [comment]
Thanks for your reply. I just created #129 , which we used to unblock our use case. The change just removes all special treatment for stdin and makes it possible for us to pass in a stream as stdin of the child process.

[https://github.com/libuv/libuv/blob/619937c783a05b51fba95cc9a62543deeffe5fa7/src/unix/process.c#L275](url)
The source code for uv_spawn() treats all fds equally - dup2 them before execvp. Therefore I think it is correct to use stream as stdin.

[https://github.com/libuv/libuv/blob/619937c783a05b51fba95cc9a62543deeffe5fa7/src/unix/process.c#L312](url)
On the other hand, uv_spawn() does have special logic for the top-3 fds. It will redirect them to /dev/null when they are either marked as UV_IGNORE (the same as the current stdin default) or missing.

Therefore, I think this change will not cause regression when uvw users spawn child processes without calling uvw::ProcessHandle::stdio() at all. However, it will cause issue when users try to configure stdin after calling uvw::ProcessHandle::stdio(FileHandle...) with other fds...

**Comment by skypjack** [comment]
I'm at work right now, I've still to look at the PR in details. However, at a first glance, you're just flipping the problem on its head and asking to users to respect the _convention_ I mentioned in the previous comment. This unlocks the possibility to use stream handles as stdin if I got it. Right?

**Comment by zxtwonder** [comment]
Yes, that's correct. The key change is in the constructor to free up stdin. The latter part is just due to the fact that poFdStdio[0] is not guaranteed to contain fd 0 any more.

**Comment by zxtwonder** [comment]
Thank you for your quick replies. It is really a pleasure to use uvw and work with you. We are building a web-to-smart hardware STEM education platform. uvw and libuv are used as the foundation for the async non-blocking on-device task scheduler. It has been very reliable and always worked as expected except this one case ;-) My name is Xintong Zhou.

**Comment by skypjack** [comment]
PR accepted thank you very much and... well, nice to meet you. I'm glad `uvw` works fine for you.
Consider to become a patron or to make a donation in future. It could make the difference for this project.
