### ISSUE TITLE
Please don't default BUILD_TESTING to ON - it messes with other projects

### ISSUE THREAD

**Issue by Qix-** [skypjack/uvw#130]
`BUILD_TESTING` is considered a 'special' option for the entire CMake environment, and is thus used across all projects that use CMake.

Explicitly defining it using `option()` is unnecessary (using it in an `if()` when it hasn't explicitly been set just results in a falsey conditional value) -- and further, specifying it as `ON` causes drastically higher compilation times for those that do not want them.

**Comment by skypjack** [comment]
Hi @Qix- I'm glad to know you use `uvw`. Can you make a PR for this?

**Comment by Qix-** [comment]
Absolutely :)

**Comment by skypjack** [comment]
Thank you. I'm a bit short in time. Much appreciated.

**Comment by skypjack** [comment]
Just out of curiosity and while waiting for the CI: for what are you using `uvw` (if you can say it, of course)?

**Comment by Qix-** [comment]
Can't describe the project, but I'm using it to drive the UI, network, file and highly CPU intensive processes :) I haven't used it before but I came across it and figured I'd give it a shot. I use vanilla Libuv frequently but I'm trying to prototype quickly and this seems like it will save me a lot of time.
