### ISSUE TITLE
Conan Package Support

### ISSUE THREAD

**Issue by uilianries** [skypjack/uvw#135]
Hello,

Do you know about [Conan](https://conan.io)?

Conan is modern dependency and package manager for C/C++. And would be great if your library would be available via package manager for other developers.

All Conan packages are available on [Conan Center](https://bintray.com/conan/conan-center), where is possible search, install and upload any official Conan package.

As your project uses libuv, we already have such dependency solved by Conan. So you are able to run uvw with libuv pre-built.

We could support you writing a recipe and publishing your packages on Bintray.

If you have any questions, just ask :-)

Regards!

**Comment by skypjack** [comment]
Hello,

It sounds good and one cannot really say _no_ when conan.io contacts you directly with such a request! :smile:
The first problem I see is that I don't know how to write a recipe, so your help would be really appreciated, of course.

Feel free to continue the discussion here or contact me privately if you prefer.

Thanks!

**Comment by skypjack** [comment]
> Could we re-use your travis script to publish the package?

Yeah, absolutely. I did something similar with [`EnTT`](https://github.com/skypjack/entt), another project that probably is worth it to be packaged for conan.io (it's also already available on `vcpkg` actually).

> we could help you with a PR [...] We could publish only for tags.

Ok, so, if you can open a PR, I can rebase it on a dedicated branch, make required changes if required, then squash everything on `master` and create a tag for the purpose.

May I ask you also to provide me with a link to some documentation regarding writing a recipe? I'm just curious and willing to understand what's going on under the hood.

Thank you very much for your interest and your help, really appreciated.

**Comment by uilianries** [comment]
> May I ask you also to provide me with a link to some documentation regarding writing a recipe? I'm just curious and willing to understand what's going on under the hood.

Conan docs is the official place to get more information: https://docs.conan.io

As your project will run a Conan recipe on same directory, this is the best approach:

https://docs.conan.io/en/latest/creating_packages/package_repo.html

It's a python script with magic helpers. It can be combined with cmake, autotools, msbuild and many others.

Regards!

**Comment by skypjack** [comment]
@uilianries just to be sure I got it, you still plan to make a PR for this? Thanks.

**Comment by uilianries** [comment]
Yes! Probably will make a PR on this weekend.

**Comment by skypjack** [comment]
Good. Not in a rush, just curious. Take your time. Thank you. :wink:

**Comment by uilianries** [comment]
Adding Conan logo for UVW:

![conan-uvw](https://user-images.githubusercontent.com/4870173/47304146-2429e380-d5fc-11e8-9790-78594371f2ad.png)

**Comment by skypjack** [comment]
I'm closing this. Let's continue on #137 and sorry if it takes long but I'm a bit busy this week.

**Comment by uilianries** [comment]
sure!
