### ISSUE TITLE
Vcpkg Support

### ISSUE THREAD

**Issue by ras0219-msft** [skypjack/uvw#136]
Similar to #135; please make a PR onto Microsoft/vcpkg! (We should be able to keep it up-to-date after that)

Since this is header only, it should be as simple as copying the port for entt[1] into a new directory for uvw and tweaking the obvious values :)

[1] https://github.com/Microsoft/vcpkg/tree/master/ports/entt

**Comment by skypjack** [comment]
Ok, If one cannot say _no_ to conan.io, I suspect it would be foolish as well to say _no_ to Microsoft, right? :smile: 
I think I'll find the time to work on it during the weekend. Thanks for the invitation. Really appreciated.

**Comment by skypjack** [comment]
>We should be able to keep it up-to-date after that

As a side not, it looks like `EnTT` is stuck to version 2.7.2  at the moment, despite version 2.7.3 is out since a while ago.  
Am I missing something? Let me know if I'm wrong. Thank you.

**Comment by ras0219-msft** [comment]
>As a side note, it looks like EnTT is stuck to version 2.7.2 at the moment, despite version 2.7.3 is out since a while ago.

We process the upgrades in batches, and unfortunately if there are problematic libraries in the batch it can significantly slow down the processing. However, we always pull the latest at the beginning of each batch so you'll get *eventual* consistency :)

If you want to fast-track an upgrade, PR's are always accepted and a good way to handle a critical bugfix!
