### ISSUE TITLE
ErrorEvent should contain more details

### ISSUE THREAD

**Issue by ZgblKylin** [skypjack/uvw#139]
I suggest ErrorEvent contains operation details, so user can retrieve more informations.
Errors from various opertaions could identify by sub-classes of ErrorEvent, such as:
```C++
handle->on<uvw::ErrorEvent>([](const uvw::ErrorEvent &event, uvw::UdpHandle &handle) {
    switch (event.operation())
    {
        case uvw::UdpHandle::Operation::Bind:
        {
            const uvw::UdpBindFailedEvent& e = static_cast<const uvw::UdpBindFailedEvent&>(event);
            // contains uvw::Addr addr()
            break;
        }
        case uvw::UdpHandle::Operation::Send:
        {
            const uvw::UdpSendErrorEvent& e = static_cast<const uvw::UdpSendErrorEvent&>(event);
            // UdpSendErrorEvent contains same member as UDPDataEvent
            break;
        }
        default:
            break;
    }
});
client->bind(address, port);
client->send(uvw::Addr{ address , port }, std::move(dataSend), 2);
```

To achieve this, Request can be used instead of Handler class methods(like SendReq), but it's not so convenient as handler classes.

**Comment by skypjack** [comment]
Are you suggesting then to differentiate the errors according to the request that generated them?  
At a first glance, it could be possible to trigger different errors and therefore let users listen them and attach different listeners on different types, like:
```
handle->on<uvw::AnEvent>([](const uvw::AnEvent &event, uvw::UdpHandle &handle) { ... });
handle->on<uvw::AnotherEvent>([](const uvw::AnotherEvent &event, uvw::UdpHandle &handle) { ... });
```
Maybe with a sort of fallback to listen all the (other) errors through a base class.

Is this what you're looking for?

**Comment by ZgblKylin** [comment]
Yes, you get the point.
We're using uvw intergrated with a plugin-based framework with Qt, and encapsulate libuv/uvw into a plugin, convert its event into QEvent or Qt Signal.
But to end user, they needn't know the underlying details in the plugin, they just want to send/listen/receive, and know the result -- whether sucessed or failed. The information(or so called context in this situation) can be retrived indirectly by event or callback, but cannot be less than those synchronized functions.

Uvw simply publish all errors into ErrorEvent, thus, for example, when sending and receiving udp datagrams with a single UdpHandle(it's a common senario when communication with emmbed devices), it's difficult to recognize the source of an ErrorEvent: Is it a receive error, or a send error?

So we need more infomations carried by ErrorEvent, it could be subscribed by a specified subclass like:
handle->on<uvw::SpecifiedErrorEvent>([](const uvw::AnotherEvent &event, uvw::UdpHandle &handle) { ... });
or simply fallback to the base class ErrorEvent, when the details are not concerned:
handle->on<uvw::ErrorEvent>([](const uvw::ErrorEvent &event, uvw::UdpHandle &handle) { ... });


 
From: Michele Caini
Date: 2018-11-05 18:34
To: skypjack/uvw
CC: Fei Chong; Author
Subject: Re: [skypjack/uvw] ErrorEvent should contain more details (#139)
Are you suggesting then to differentiate the errors according to the request that generated them?
At a first glance, it could be possible to trigger different errors and therefore let users listen them and attach different listeners on different types, like:
handle->on<uvw::AnEvent>([](const uvw::AnEvent &event, uvw::UdpHandle &handle) { ... });
handle->on<uvw::AnotherEvent>([](const uvw::AnotherEvent &event, uvw::UdpHandle &handle) { ... });

Maybe with a sort of fallback to listen all the (other) errors through a base class.
Is this what you're looking for?
―

**Comment by skypjack** [comment]
Wouldn't be enough to be able to replace the error listener when you start a new request instead?  
Not sure it's possible at the moment actually, but it would be easier to develop and to maintain.

**Comment by ZgblKylin** [comment]
If send data by SendReq, a specified listener can be used, but it's not as convenient as UdpHandle::send.
However, when send data by UdpHandle::send, only ErrorEvent can be used, it can't be replaced.



 
From: Michele Caini
Date: 2018-11-05 19:46
To: skypjack/uvw
CC: Fei Chong; Author
Subject: Re: [skypjack/uvw] ErrorEvent should contain more details (#139)
Wouldn't be enough to be able to replace the error listener when you start a new request instead?
Not sure it's possible at the moment actually, but it would be easier to develop and to maintain.

**Comment by skypjack** [comment]
What I meant is that you can use either [the connection object returned by `on` or `once`](https://github.com/skypjack/uvw/blob/master/src/uvw/emitter.hpp#L240) or [the member function template `clear`](https://github.com/skypjack/uvw/blob/master/src/uvw/emitter.hpp#L277) to remove the listener previously attached to a handle and this replace it.  
It means that you can attach a listener to the error event when you bind a handle, then you can remove it on the success callback and attach a dedicated listener for to treat errors received during a send.  
It's close to what you do with `libuv`, where you pass callbacks to each and every (async) function you call, so as to be notified when they return.

In other terms, there is already built-in support to do what you are suggesting.

Note also that the error event [returns also the underlying code](https://github.com/skypjack/uvw/blob/master/src/uvw/emitter.hpp#L67). [Here](http://docs.libuv.org/en/v1.x/errors.html) is the full reference.  
One can infer the actual type from this code and forward an application-specific error in case.

**Comment by ZgblKylin** [comment]
Remove and reset listener is a good idea for operations like bind, but still, two asynchronous operations running concurrently cannot tell apart by listener, e.g,  send and receive by a single handle.
However, there're still some ways to workaround:
1. Resolve the error code manually, but need going through libuv source code to find which codes will be thown.
2. Encapsulate a customized recv/write function, using specified event instead of standard function.
I think the 2nd way is better, I can replace the recv/write/listen function by customized version, and deal with other operations by replacing the listener.

**Comment by skypjack** [comment]
>two asynchronous operations running concurrently cannot tell apart by listener

Granted. It makes sense.

>Resolve the error code manually, but need going through libuv source code to find which codes will be thown.

I understand users of `uvw` don't want to do it usually. :smile: 

>Encapsulate a customized recv/write function, using specified event instead of standard function.

Yeah. Probably it would be good to update `uvw` so that it triggers different error events. It sounds like an interesting feature and it's worth it to keep open the issue. Hopefully, sooner or later I'll have enough free time to work on it too.  

Unfortunately, at the moment `uvw` is in maintenance mode and I don't have much time to spend on it.  
At a first glance, this change requires some efforts, mainly because error management is almost entirely centralized in functions like [this one](https://github.com/skypjack/uvw/blob/master/src/uvw/handle.hpp#L61). What you're asking for is to move everything at the call site of `invoke`. It involves great part of the codebase and I don't want to/cannot do it only for udp handles for obvious reasons after all.

**Comment by ZgblKylin** [comment]
yes, libuv is not just a simple network library with udp/tcp, there're other functionalities also use callback and event, adding feature for specification requires a large amount of efforts.
I'll use customized functions for instead, and look forward for updates. I could commit my customization to [my branch](https://github.com/ZgblKylin/uvw-cpp11), it may be helpful for future improvement.

**Comment by skypjack** [comment]
It would be good. If you come up with a good idea, I'll get the best out of it to improve `uvw`. :wink:

**Comment by skypjack** [comment]
I thought about this. I think I'll close the issue as _won't fix_.  
Reasons are that it would add to the library another bunch of template parameters around and increase a bit the complexity, when this can and should be implemented probably application side only in those cases where one is actually interested in differentiating errors.  
Implementing it is quite easy in fact, even in a centralized manner. Handles are public event emitters for themselves, so it would be enough to attach a listener on the `ErrorEvent`, decode the error code and republish a custom event on the same handle at once. Because of the nature of the event emitter, all of this is synchronous, so there is no risk to work with an invalid handle or whatever.

Any thought?
