### ISSUE TITLE
Rename UDP to Udp

### ISSUE THREAD

**Issue by ZgblKylin** [skypjack/uvw#140]
I suggest rename all `UDP` in class names such as `UDPDataEvent` and `UDPHandle` to `Udp`, to get consistency with those `Tcp` classes which already use camel-case rather than uppercase.

**Comment by skypjack** [comment]
I knew sooner or later someone would have asked it... :joy:

**Comment by skypjack** [comment]
Btw I'd rather change `TcpHandle` in `TCPHandle` instead of the other way around with UDP.  
It's somehow more _correct_, also referring to their RFC.

**Comment by ZgblKylin** [comment]
haha, either would be ok.

**Comment by skypjack** [comment]
Upstream.
