### ISSUE TITLE
Conan builds failing due to libuv/1.25.0@bincrafters/stable missing requirement

### ISSUE THREAD

**Issue by danimtb** [skypjack/uvw#144]
Hi!

I was trying the recipe for this library and seems the requirement for libuv 1.25.0 is not in Conan Center yet. Also found the CI with latest changes is failing:  https://travis-ci.org/skypjack/uvw/jobs/483890012

Probably we would need to package the new version of libuv (cc/ @uilianries) and meanwhile revert this?

Another suggestion would be to fix the VCS field in https://bintray.com/skypjack/conan/uvw:skypjack and write the github URL there.

Thanks!

**Comment by uilianries** [comment]
Hello everyone!

I just published the new branch for libuv/1.25:

https://github.com/bincrafters/conan-libuv/tree/testing/1.25

We need to wait for CI results and promote it in a stable branch. It will take some hours, so I'll update this thread when it's ready.

**Comment by uilianries** [comment]
Yes, but please, just update the VCS field, as mentioned by Daniel

> Another suggestion would be to fix the VCS field in bintray.com/skypjack/conan/uvw:skypjack and write the github URL there.

**Comment by danimtb** [comment]
Thanks a lot for the fix @uilianries 😄 I will try to review the conan center inclusion request ASAP
