### ISSUE TITLE
FileReq::data data member shadows Resource::data member function

### ISSUE THREAD

**Issue by wtdcode** [skypjack/uvw#147]
We know that the `FileReq` is inherited from `Request` and `Request` is inherited from `Resource`. However, `FileReq` has a data member `FileReq::data` whose name is same as `Resource::data` member function. Therefore, I have to call `Resource::data` like this:

```
req->uvw::Resource<uvw::FileReq, uv_fs_t>::data(ctx);
```

which is quite not elegant and annoying since I have to know the template arguments of `Resource`.

**Comment by skypjack** [comment]
What name would be good for that?

**Comment by wtdcode** [comment]
I'm not so sure. Perhaps `m_data` is a good choice but it will break the code style.

**Comment by skypjack** [comment]
I think I'm missing something. `FileReq` has no public member named `data`. Is the private one that gives you an error?

**Comment by wtdcode** [comment]
Yes.

That's true for MSVC (but I haven't tried to compile). Intellisense seems to think `FileReq::data` has an operator `()` overloading function.

**Comment by skypjack** [comment]
Oh, ok, sorry, I didn't get it initially. So who cares of the name after all.  
I'll change it the soonest. Thank you for reporting it.

**Comment by skypjack** [comment]
Upstream. Let me know if it works for you.

**Comment by wtdcode** [comment]
It should work now. Thanks for your support.
