### ISSUE TITLE
Release loop when close success

### ISSUE THREAD

**Issue by Noisyfox** [skypjack/uvw#152]
Currently the `uvw::Loop` will call `Loop::close()` in destructor function if `loop` is not null which calls `uv_loop_close()`. However `uv_loop_close()` is not idempotent (it will return UV_EBUSY if the loop has already been closed in DEBUG build, or crash straight away in Release build) which means if I manually called `Loop::close()` and it success, then the process will crash when it try to destruct the object.

A workaround I could come up with is in `Loop::close` if the return error is 0 then reset the `loop` ptr. Then move the nullptr check from destroctor to `Loop::close` instead.

The following code could easily reproduce this:
```cpp
#include <uvw.hpp>

int main()
{
	auto loop = uvw::Loop::getDefault();

	loop->on<uvw::ErrorEvent>([](const uvw::ErrorEvent& ev, uvw::Loop& l)
	{
		printf("Error!");
		if (ev.code() == UV_EBUSY)
		{
			l.walk([](uvw::BaseHandle& h)
			{
				h.close();
			});
		}
	});

	loop->close();
}
```

Build with VS2017 on windows.

In debug mode it will crash at:
![image](https://user-images.githubusercontent.com/1537155/58391943-11d4c400-807b-11e9-92ef-264e3b83162c.png)

While in release mode it will crash at:
![image](https://user-images.githubusercontent.com/1537155/58391911-fe295d80-807a-11e9-8067-8d0e7db3c95c.png)

**Comment by skypjack** [comment]
>However uv_loop_close() is not idempotent (it will return UV_EBUSY if the loop has already been closed in DEBUG build, or crash straight away in Release build)

Interesting. Actually the [documentation](http://docs.libuv.org/en/v1.x/loop.html#c.uv_loop_close) says something slightly different:

>Call this function only when the loop has finished executing and all open handles and requests have been closed, or it will return UV_EBUSY.

It seems that `UV_EBUSY` is due to pending handles or requests instead.  
Are you sure you've none of them?

**Comment by skypjack** [comment]
In terms of consistency, the best bet is to remove the destructor of the loop and let it be a no-op.  
`uvw` stays true to the behavior of `libuv` and you've eg to close handles explicitly, it won't close them for you. I don't see why it should close the loop implicitly.  
I'm tempted to say that you pointed out a design issue rather then a bug.

**Comment by Noisyfox** [comment]
> It seems that UV_EBUSY is due to pending handles or requests instead.
> Are you sure you've none of them?

The issue happens only in debug mode because of [this](https://github.com/libuv/libuv/blob/4a4c9a688fa2a7fad056f48304a583927044b935/src/uv-common.c#L767).

>I'm tempted to say that you pointed out a design issue rather then a bug.

My understanding is that if the loop contains any active handles / requests then there will be references to the loop so the destruction won't be called automatically, so the `Loop::close()` actually should not be called explicitly?

This seems quite reasonable since if the `Loop` get destructed but `uv_loop_close()` returns `UV_EBUSY` then that means something is wrong with the reference counter. In this case is not the fault of this library.

However this makes the `Loop::close()` function very confusing -- it's public but you are not supposed to call it.

**Comment by skypjack** [comment]
Quite the opposite.

What I'm saying is that the `Loop` class should not invoke `uv_loop_close`. Actually, `uvw::Loop` should not have an explicitly defined destructor at all.  
Instead, you as an user **must** close explicitly the loop as you would do if you were working directly with `libuv`. The same happens with the handles after all. This means _staying true to the underlying library_ and that's why I think it's a design flaw rather than an issue.

**Comment by Noisyfox** [comment]
Right that make sense.

**Comment by skypjack** [comment]
I must admit that, although it actually makes sense, it would be probably a breaking change. I'm not sure it's the best choice.  
On the other side, to solve the issue you pointed out it's enough to update the `close` member function as follows:

```
    void close() {
        auto err = uv_loop_close(loop.get());
        if(err) { publish(ErrorEvent{err}); }
        else { loop.reset(); }
    }
```
