### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by maingig** [skypjack/uvw#164]
Do you have a good example of getting keyboard input (linux)?  Given that it's a stream, does the setup model the tcp example?

I have  this at the moment but am having trouble getting console input. Thanks.

```
    m_input = m_loop->resource<uvw::TTYHandle>(uvw::StdIN, true);
    if (m_input) {
        m_input->mode(uvw::TTYHandle::Mode::NORMAL);
        m_input->on<uvw::DataEvent>([&](const uvw::DataEvent &event, uvw::TTYHandle &) {
            // emit event
            inputEvent(event.data.get(), event.length);
        });
        // initialize
        if (m_input->init()) {
            m_input->read();
        }
    }
```

**Comment by skypjack** [comment]
>Do you have a good example of getting keyboard input (linux)? Given that it's a stream, does the setup model the tcp example?

Unfortunately, I've not a good example for you. I'm sorry.
FWIW `uvw` adds nothing to `libuv`. It's just a tiny wrapper around the underlying library that adds automatic resource/memory management and a few other things, other than making the whole thing less _C-ish_.  
If I were you, I'd look for a good example of getting keyboard input with `libuv`, then I'd _traduce_ it to `uvw`. The latter should be straightforward.
