### ISSUE TITLE
Petition for a C++11 version

### ISSUE THREAD

**Issue by sidyhe** [skypjack/uvw#168]
Hi!
I am using uvw for my code
there is no cpp17 because my gcc is 4.9.2
by using the cpp11 branch, i encount the bug same as #152 
hope that keep code of cpp11 new, not everyone has cpp17 env
thanks

**Comment by skypjack** [comment]
There are two things I'd like to do here:

* Port `uvw` to C++11.
* Introduce a _dual model_, that is a header-only version for fast integration and a compiled version for long term uses.

Both require quite a lot of work but the project is designed in such a way that it would be possible to achieve these goals easily.

However, I'm no longer actively using this library and therefore I'm already doing my best to maintain it and update `uvw` when a new version of `libuv` is released.
Afaik (also from the mail I receive actually) there are several users and companies that use this project but apparently nobody is interested in contributing and probably I haven't put enough efforts to explain that the _sponsor_ button is there for a reason.

Unfortunately I haven't enough bandwidth right now to work on the two points above and to maintain two versions of the library, C++17 and C++11.
I'd be glad to do that if someone is willing to sponsor `uvw` and I'm available for reviewing contributions in this sense if someone pops up with a good PR that covers the codebase as a whole and not only for the part of interest.

I'll leave this issue open for some time. Let's see if someone is interested in the proposal. :+1:

**Comment by sidyhe** [comment]
ok, i see, whatever, the project inspire me a lot, thank you anyway.

**Comment by coolxv** [comment]
hope that keep code of cpp11 new
thanks

**Comment by skypjack** [comment]
Let's see how many requests we collect in a month before to decide if it's worth it. :+1: 
Spread the petition around! :wink:

**Comment by skypjack** [comment]
Time to close this issue. Thank you for participating.
