### ISSUE TITLE
Trying to write a uvw::TCPHandle over a uvw::PipeHandle fails

### ISSUE THREAD

**Issue by blattersturm** [skypjack/uvw#169]
The following code:

```cpp
auto clientHandle = m_server->loop().resource<uvw::TCPHandle>();
// ... where m_dispatchPipes is a list of PipeHandle pointers
m_dispatchPipes[index]->write(*clientHandle, dummyMessage, sizeof(dummyMessage));
```

leads to the following compiler error (on MSVC16.4):
```
error C2248: 'uvw::UnderlyingType<T,U>::get': cannot access protected member declared in class 'uvw::UnderlyingType<T,U>'
        with
        [
            T=uvw::TCPHandle,
            U=uv_tcp_t
        ]
```

on the line
```cpp
req->write(this->template get<uv_stream_t>(), send.template get<uv_stream_t>());
```

I'm not sure if I'm doing something wrong here, or if there's actually an issue with marking as `friend` either in the library or the compiler, but this ought to be working - and I don't see any tests for IPC pipes either.

**Comment by skypjack** [comment]
Hi, sorry if I'm late but I've been very busy during the last days.
May I ask you what's the equivalent form in `libuv`? This could speed up the development.

>I don't see any tests for IPC pipes either.

Actually, if you could provide a minimal, reproducible example for this use case, we could use it as a test to avoid regressions in future.
Is it possible to pack a few lines together that also reproduce this error?

**Comment by blattersturm** [comment]
>  May I ask you what's the equivalent form in `libuv`? This could speed up the development.

I encountered it while porting [this C# code](https://github.com/dotnet/aspnetcore/blob/0517745c08d1bc85009f1ca41a41d77176eeea60/src/Servers/Kestrel/Transport.Libuv/src/Internal/ListenerPrimary.cs#L121) which practically calls uv_write2 to send the TCP handle for an accepted socket over a pipe to a different thread.

As per the libuv docs:

> Extended write function for sending handles over a pipe. The pipe must be initialized with ipc == 1.
> **Note** send_handle must be a TCP socket or pipe, which is a server or a connection (listening or connected state). Bound sockets or pipes will be assumed to be servers.



>  Is it possible to pack a few lines together that also reproduce this error?

Not sure, it might be able to trivially modify the pipe test to send a pipe and then call an uv_accept equivalent on the pipe in uvw::DataEvent handler (as I ended up doing in my application with the protection level temporarily patched into `public:`) but it'd be a weird combination of a socket and pipe example this way.

**Comment by skypjack** [comment]
Oh, yeah, got it. I've used the wrong `get` method within `write`.
The fix is trivial. I'll push it upstream as soon as I reach a wifi. :+1:
