### ISSUE TITLE
Make More Examples

### ISSUE THREAD

**Issue by lindyer** [skypjack/uvw#170]
Please make more examples, Thanks. 
Best Regard!

**Comment by skypjack** [comment]
It won't happen. I'm sorry.

I'm no longer using this library in real world projects and I barely find the time to keep it up-to-date.
Moreover, despite the many users, apparently nobody is willing to maintain, contribute or fund it.

There are several _improvements_ I'd like to do to the codebase (full compatibility with C++11, dual model header-only plus compiled library, more tests and examples, and so on) but I've not enough bandwidth for that at the moment.
If you like to write examples, I can review the PRs and help to make them suitable for the merge though.
