### ISSUE TITLE
Allow passing unique_ptr with any deleter

### ISSUE THREAD

**Issue by imachug** [skypjack/uvw#182]
Consider an external C function that allocates memory with `malloc`. I want to send the data over a TCP socket, but `TCPHandle::write` only accepts `unique_ptr<char[], default_delete<char[]>>`. Can passing a custom deleter be implemented?

**Comment by skypjack** [comment]
I think it's possible actually. Supporting all types of deleters can be tricky though while constraining the signature to something more specific may be easier to implement and work with.
I've to try it though, so let's see. What do you suggest exactly? Is having a `void(*)(char *)` like deleter enough from your point of view?

**Comment by skypjack** [comment]
See if branch `experimental` is what you expect. Thanks.
I'm looking forward to your feedback.

**Comment by imachug** [comment]
Yes, it solves my problem. Thanks!
