### ISSUE TITLE
`make install' requires gtest and tests to be built

### ISSUE THREAD

**Issue by stefanofiorentino** [skypjack/uvw#186]
`sudo make install` under Linux requires the test targets to be build [because under the  `all' target]

**Comment by skypjack** [comment]
Isn't there a flag already to exclude them? Something like `-DBUILD_TEST=OFF` (out of my mind since I'm from mobile).

**Comment by stefanofiorentino** [comment]
Yes there is that flag. 
I'm just wondering if installing gtest/gmock and tests in /usr/local/lib makes any sense.
I'll investigate this further.

**Comment by skypjack** [comment]
Oh... I didn't get it's installing them too. Good catch.

**Comment by skypjack** [comment]
You should put a `close #N` in your commit messages to have your issues closed automatically when things get merged on `master`. :wink:

**Comment by stefanofiorentino** [comment]
Just want to avoid you deliberately merge it into master. 
Joking, should I force-push?

**Comment by skypjack** [comment]
Nah, just a suggestion for the next time. We can still close this one as usual. :+1:

**Comment by skypjack** [comment]
Merged on `master`.
