### ISSUE TITLE
Closed handle still referenced and in closing state

### ISSUE THREAD

**Issue by h3ndrk** [skypjack/uvw#188]
Thanks for the great library!

I'm currently trying to gracefully terminate the libuv loop. Inspired by [https://stackoverflow.com/q/22363036 (SOLVED section of the question)](https://stackoverflow.com/q/22363036), I'm trying to use a long-lived `AsyncHandle` which acts as the only work of the loop. I'm expecting that closing the handle should also terminate the loop, but in my following example, the loop keeps running forever:

```cpp
// get the default loop
auto loop = uvw::Loop::getDefault();
// create a variable for a thread outside of the following scope (next line)
std::thread loopThread;
{
  // here an async handle is created
  auto asyncHandle = loop->resource<uvw::AsyncHandle>();
  // now the thread for the loop gets started
  loopThread = std::thread{[loop] {
    std::cout << "Entering libuv loop ..." << std::endl;
    loop->run();
    std::cout << "Exited libuv loop." << std::endl;
  }};

  // just a little delay
  std::this_thread::sleep_for(1s);

  // some debug output ...
  std::cout << "loop->alive(): " << loop->alive() << std::endl;
  std::cout << "asyncHandle->active(): " << asyncHandle->active() << std::endl;

  // closing the handle
  assert(asyncHandle->active());
  asyncHandle->close();
  assert(!asyncHandle->active());

  // deleting the handle
  asyncHandle.reset();

  // leaving the scope, one more possibility for the handle to get deleted (but should be
  // deleted already)
}

// more debug output ...
std::cout << "loop->alive(): " << loop->alive() << std::endl;
loop->walk([](uvw::BaseHandle& handle) {
  std::cout << "active: " << handle.active() << ", category: " << handle.category()
            << ", type: " << static_cast<int>(handle.type())
            << ", referenced: " << handle.referenced() << ", closing: " << handle.closing()
            << std::endl;
});

// another short delay
std::this_thread::sleep_for(1s);

// even more debug output ...
loop->walk([](uvw::BaseHandle& handle) {
  std::cout << "active: " << handle.active() << ", category: " << handle.category()
            << ", type: " << static_cast<int>(handle.type())
            << ", referenced: " << handle.referenced() << ", closing: " << handle.closing()
            << std::endl;
});

// joining the thread (here, the std::this_thread blocks because loopThread will not terminate)
if (loopThread.joinable())
{
  loopThread.join();
}
```

Program output:

```
Entering libuv loop ...
loop->alive(): 1
asyncHandle->active(): 1
loop->alive(): 1
active: 0, category: 1, type: 1, referenced: 1, closing: 1
active: 0, category: 1, type: 1, referenced: 1, closing: 1
^C
```

Interestingly, `referenced()` and `closing()` both return `true`. This looks odd...

Does somebody have a suggestion for using a handle to keep the loop running until it gets closed?

I would like to not use `uvw::Loop::stop()`, if possible. I like the idea, that `uvw::Loop::run()` returns when there is no more work to do. It also saves me to check if the loop is still running each time I want to dispatch more asynchronous operations.

Thanks in advance!

**Comment by stefanofiorentino** [comment]
@h3ndrk I think there is a race-conditions overhere. In fact if you `break` execution at line loop->run(); and after `continue` the code gracefully ends. I wouldn't mix std::thread with the the event loop.
I've created an example [here](https://gist.github.com/stefanofiorentino/199ada95df08c9c8fcc14bf8fa61cd30).

**Comment by h3ndrk** [comment]
@stefanofiorentino Thanks for your quick answer! I looked at your example for a while. If I understand it correctly, you swapped the two threads: In my example, the main thread does other work and the loop runs in a separate thread. Resource initialization is done in the main thread. In your example it is the other way, the main thread does the initialization and runs the main loop, other work is done in a separate thread.

My reasoning for my threading was to keep the main thread a managing thread which starts 3rd party event loops. (I want to also use Boost.Fiber in conjunction with uvw. Boost.Fiber requires its own worker threads which I also want to start from the main thread.) This might not be the best design, I'm open for feedback!

I implemented your idle-handle-approach with `std::thread` and my threading design. This time I strictly initialize all resources in the loop thread:

```cpp
#include <chrono>
#include <iostream>
#include <memory>
#include <thread>
#include <uvw.hpp>

int main (void)
{
  using namespace std::chrono_literals;

#define USE_IDLE_HANDLE 0
  // create an empty async handle
  std::shared_ptr<uvw::AsyncHandle> asyncHandle;

  // start the loop thread
  std::thread loopThread{[](std::shared_ptr<uvw::AsyncHandle>& asyncHandle) {
                            std::cout << "Entering thread ..." << std::endl;

                            // get the default loop
                            auto loop = uvw::Loop::getDefault();

#if USE_IDLE_HANDLE == 1
                            // create an idle handle to keep the loop running
                            auto idleHandle = loop->resource<uvw::IdleHandle>();
                            idleHandle->start();
#endif

                            // create an async handle for closing
                            asyncHandle = loop->resource<uvw::AsyncHandle>();
                            asyncHandle->on<uvw::CloseEvent>([
#if USE_IDLE_HANDLE == 1
                              idleHandle
#endif
                            ](const auto&, auto&) {
                              std::cout << "close event" << std::endl;
#if USE_IDLE_HANDLE == 1
                              idleHandle->stop();
                              idleHandle->close();
#endif
                            });

                            // actually run the loop
                            loop->run();

                            std::cout << "Exiting thread ..." << std::endl;
                          },
                          std::ref(asyncHandle)};

  std::cout << "Sleeping ..." << std::endl;
  // sleep (as a way to lazily synchronize the thread reaching loop->run() => asyncHandle has been
  // populated)
  std::this_thread::sleep_for(1s);

  std::cout << "Trying to close ..." << std::endl;
  // close the async handle
  if (asyncHandle)
  {
    std::cout << "Actually closing ..." << std::endl;
    asyncHandle->close();
  }

  std::cout << "Trying to join the thread ..." << std::endl;
  if (loopThread.joinable())
  {
    std::cout << "Actually joining thread ..." << std::endl;
    loopThread.join();
  }
  std::cout << "Terminated" << std::endl;

  return 0;
}
```

Program output with `#define USE_IDLE_HANDLE 1` (everything looks fine):

```
Entering thread ...
Sleeping ...
Trying to close ...
Actually closing ...
Trying to join the thread ...
Actually joining thread ...
close event
Exiting thread ...
Terminated
```

Program output with `#define USE_IDLE_HANDLE 0` (loop does not terminate):

```
Entering thread ...
Sleeping ...
Trying to close ...
Actually closing ...
Trying to join the thread ...
Actually joining thread ...
^C
```

So, without the idle handle, the async handle close callback does not fire. **Why is that?** [According to the StackOverflow question](https://stackoverflow.com/q/22363036), in plain libuv only a async handle should work (have not tested that), but with uvw this does not work... As discovered in my [previous example above](https://github.com/skypjack/uvw/issues/188#issue-591481741), the async handle keeps being referenced and in closing state. In general, I would like to avoid introducing an additional idle handle that might not be necessary.

**According `uvw::Loop::stop()`:** In contrast to your example, my example is not using `uvw::Loop::stop()` which I wanted to avoid (see reasoning in my previous comment). It only closes the async handle.

**According `std::thread`-avoidance:** I looked at `uvw::Thread::run()` which uses `uv_thread_create()` [(source code)](https://github.com/libuv/libuv/blob/v1.x/src/unix/thread.c#L209-L264). This means libuv uses plain pthreads (on Unix) without interacting with any loop. I guess this is the same for `std::thread`, so we should not see any difference in using one or the other.

**Comment by h3ndrk** [comment]
Did the test with plain libuv:

```cpp
#include <chrono>
#include <iostream>
#include <thread>
#include <uv.h>

#define USE_IDLE_HANDLE 1

typedef struct
{
#if USE_IDLE_HANDLE == 1
  uv_idle_t* idleHandle;
#endif
  uv_async_t* asyncHandle;
} user_data_t;


void sendEvent(uv_async_t* handle)
{
  user_data_t* userData = reinterpret_cast<user_data_t*>(handle->data);

  std::cout << "send event" << std::endl;

  uv_close(reinterpret_cast<uv_handle_t*>(userData->asyncHandle), nullptr);
#if USE_IDLE_HANDLE == 1
  uv_idle_stop(userData->idleHandle);
  uv_close(reinterpret_cast<uv_handle_t*>(userData->idleHandle), nullptr);
#endif
}


int main(void)
{
  using namespace std::chrono_literals;

#if USE_IDLE_HANDLE == 1
  // create an empty idle handle
  uv_idle_t idleHandle;
#endif

  // create an empty async handle
  uv_async_t asyncHandle;

  // start the loop thread
  std::thread loopThread
  {
    [](
#if USE_IDLE_HANDLE == 1
        uv_idle_t* idleHandle,
#endif
        uv_async_t* asyncHandle) {
      std::cout << "Entering thread ..." << std::endl;

      // get the default loop
      auto loop = uv_default_loop();

#if USE_IDLE_HANDLE == 1
      // create an idle handle to keep the loop running
      uv_idle_init(loop, idleHandle);
      uv_idle_start(idleHandle, nullptr);
#endif

      // create an async handle for closing
      uv_async_init(loop, asyncHandle, sendEvent);
      user_data_t userData
      {
#if USE_IDLE_HANDLE == 1
        idleHandle,
#endif
            asyncHandle
      };
      asyncHandle->data = &userData;

      // actually run the loop
      uv_run(loop, UV_RUN_DEFAULT);

      std::cout << "Exiting thread ..." << std::endl;
    },
#if USE_IDLE_HANDLE == 1
        &idleHandle,
#endif
        &asyncHandle
  };

  std::cout << "Sleeping ..." << std::endl;
  // sleep (as a way to lazily synchronize the thread reaching loop->run() => asyncHandle has been
  // populated)
  std::this_thread::sleep_for(1s);

  std::cout << "Trying to close ..." << std::endl;
  // close the async handle
  uv_async_send(&asyncHandle);

  std::cout << "Trying to join the thread ..." << std::endl;
  if (loopThread.joinable())
  {
    std::cout << "Actually joining thread ..." << std::endl;
    loopThread.join();
  }
  std::cout << "Terminated" << std::endl;

  return 0;
}
```

This C program works with `#define USE_IDLE_HANDLE 1` and `#define USE_IDLE_HANDLE 0`.

One change from the C++ program with uvw is that I now use `uv_async_send()` instead of `uv_close()` which is not thread-safe and should only be called from within the loop thread.

I will now revisit the C++ program again to use `uvw::AsyncHandle::send()` instead of `close()` and be even more strict in which thread operations are done.

**Comment by stefanofiorentino** [comment]
Could this fiber doc be helpful?
https://www.boost.org/doc/libs/1_67_0/libs/fiber/doc/html/fiber/integration/event_driven_program.html
I'll try to review your code asap.

**Comment by h3ndrk** [comment]
When applying the following patch to the [C++ program with uvw](https://github.com/skypjack/uvw/issues/188#issuecomment-607146263), `#define USE_IDLE_HANDLE 1` and `#define USE_IDLE_HANDLE 0` work both (both cases terminate the loop):

```diff
@@ -27,12 +27,13 @@
 
                            // create an async handle for closing
                            asyncHandle = loop->resource<uvw::AsyncHandle>();
-                           asyncHandle->on<uvw::CloseEvent>([
+                           asyncHandle->on<uvw::AsyncEvent>([
 #if USE_IDLE_HANDLE == 1
                                                                 idleHandle
 #endif
-                           ](const auto&, auto&) {
+                           ](const auto&, auto& handle) {
                              std::cout << "close event" << std::endl;
+                             handle.close();
 #if USE_IDLE_HANDLE == 1
                              idleHandle->stop();
                              idleHandle->close();
@@ -56,7 +57,7 @@
   if (asyncHandle)
   {
     std::cout << "Actually closing ..." << std::endl;
-    asyncHandle->close();
+    asyncHandle->send();
   }
 
   std::cout << "Trying to join the thread ..." << std::endl;
```

So in conclusion, the problem was that I tried closing handles from outside the loop thread. Instead, when using `uvw::AsyncHandle::send()` the loop gets terminated as expected.

I will look into your link shortly, so I will not close this issue now.

**Comment by h3ndrk** [comment]
I need to review more closely whether Boost.Fiber is still a good fit. Maybe just libuv+uvw fits better.

Closing this for now, thanks for your help @stefanofiorentino!
