### ISSUE TITLE
cmake_minimum_required set higher than neccesary

### ISSUE THREAD

**Issue by jameshilliard** [skypjack/uvw#194]
It seems the [cmake_minimum_required](https://github.com/skypjack/uvw/blob/v2.5.0_libuv-v1.37/CMakeLists.txt#L5) was bumped up from version `3.2` all the way to `3.15.3` in [this commit](https://github.com/skypjack/uvw/commit/55d7782af5654cde8bba89071e13d240fd27ff3b), it doesn't appear `3.15.3` is the actual minimum especially being a point release that doesn't seem to have added any major features. To make it easier to compile on older systems cmake_minimum_required should be set to the actual minimum.

**Comment by skypjack** [comment]
What would be a _reasonable_ minimum for older systems?
Afaik, some features at least from 3.12 have been used, so we cannot do more than this without reviewing the build system as a whole.

**Comment by jameshilliard** [comment]
> What would be a reasonable minimum for older systems?

Well it should probably just be the minimum that uvw actually needs rather than something arbitrary. The build system I ran into this issue on is [buildroot](https://buildroot.org/) which is currently setting the minimum cmake version to 3.10, if it really needs to be raised beyond that it can be without much trouble but doing so would slow down builds as raising the minimum cmake version would trigger buildroot to compile the newer cmake from source when the build host system doesn't have a cmake that meets the minimum requirements.

> Afaik, some features at least from 3.12 have been used, so we cannot do more than this without reviewing the build system as a whole.

Oh, I'm curious which features would those be? We haven't run across any packages requiring anything newer than 3.10 aside from uvw so far.

**Comment by skypjack** [comment]
Actually it's not 3.12, it's 3.11.4 because of `FetchContent_Declare`.

**Comment by stefanofiorentino** [comment]
I think we also have something from [3.13](https://cmake.org/cmake/help/v3.13/release/3.13.html#commands). See the policy [CMP0079](https://cmake.org/cmake/help/v3.13/policy/CMP0079.html#policy:CMP0079).

**Comment by asafkahlon** [comment]
Can you please specify where exactly do you use that feature?
I was able to compile the package (including docs and tests) with CMake=3.12.

The command I used to generate the Makefile was:
`cmake . -DBUILD_DOCS=ON -DBUILD_TESTING=ON -Bbuild`

**Comment by stefanofiorentino** [comment]
@asafkahlon did you try a broader set of configuration option as `USE_ASAN` or the new `BUILD_UVW_LIBS` (ed. which allows for static/shared libs to be built)?

**Comment by skypjack** [comment]
Ok, so? v3.13 is the one to set in the `CMakeLists.txt`?
Surely, we can't easily switch back to v3.2 and it's not even something I'd like to do to be honest.

**Comment by asafkahlon** [comment]
Yeah, I think 3.13 would be the correct version.
And I agree we shouldn't switch back to 3.2...

**Comment by jameshilliard** [comment]
@skypjack [Readme requirements section](https://github.com/skypjack/uvw/blob/master/README.md#requirements) should be updated to reflect that the minimum cmake is 3.13.

**Comment by skypjack** [comment]
Right. Thanks for pointing this out. :+1: Updated.
