### ISSUE TITLE
UDPDataEvent's data member is const

### ISSUE THREAD

**Issue by elindsey** [skypjack/uvw#200]
[UDPDataEvent's data member](https://github.com/skypjack/uvw/blob/master/src/uvw/udp.h#L35) has type `std::unique_ptr<const char[]> data`. This makes for an awkward API - if I want to write a UDP-based proxy, or if I want to do the (very common) DNS echo server example where I read in a request, modify a few fields in place, and send it as a response then I'm forced to either cast away const or do a memcpy.

It looks like streams used to have the same problem, but were fixed to be non-const: https://github.com/skypjack/uvw/commit/dd1f45ea197c0914739baae252dbcefa144d9b63
Can UDPDataEvent be fixed in a similar fashion?

**Comment by skypjack** [comment]
It makes perfectly sense actually. Thanks for pointing this out.
May I ask you to test branch `experimental` and let me know if it works as expected now?

**Comment by elindsey** [comment]
I just tested and it all works as expected. Thank you! 🙂

**Comment by skypjack** [comment]
You're welcome. Thank you for testing it. :+1:
