### ISSUE TITLE
update doc

### ISSUE THREAD

**Issue by Macfly** [skypjack/uvw#202]
Hello,
Is it possible to update the doc in https://skypjack.github.io/uvw/index.html

I try to build it locally but it doesn't work.

Thanks

**Comment by skypjack** [comment]
Oh, yeah, my fault. I'm updating it. Thanks for pointing this out. :+1:

**Comment by skypjack** [comment]
Done. Online soon.

**Comment by skypjack** [comment]
I've just realized that the online doc isn't correctly generated.
I'm updating it soon. There is already another issue for that, so I won't reopen this since they are duplicate anyway.
