### ISSUE TITLE
Lost functionalities on Write

### ISSUE THREAD

**Issue by nicolasnoble** [skypjack/uvw#203]
There are two functionalities I am currently missing from using raw libuv.

The first one is the ability to issue a write request over multiple buffers. Right now the internal `WriteReq` object is hardcoded to invoke `uv_write` with only a single buffer. This is mostly relevant with the second missing functionality:

The second one is that there is no distinction between write requests when the `WriteEvent` is being fired. The `write` method returns a void, instead of exposing the `WriteReq`, and then it delegates the `WriteEvent` to its `StreamHandle`.

Ideally, one ought to be able to:

 - pass more than one buffer to `write`, and
 - receive a `WriteReq` as a response, that is then referenced into the `WriteEvent` being fired later.

The rationale is that depending on what sort of data being sent, a packet being sent may be for example constructed with a fixed header, a fixed footer, and a variable body for example, or a different combination thereof, this being the basic scatter-gather principle. Being able to manage the memory resource for the whole reconstructed write request if a fairly useful feature, which is currently missing.

**Comment by nicolasnoble** [comment]
The first issue seems to be doable using another overload of the `write` method. Memory management in this case is fully on the caller's, and the API doesn't take any ownership for any of the buffers. 

An easy solution that doesn't break API for the second part would be to make `write` return a token of type `uintptr_t`, which will be guaranteed unique across all pending write requests. It'd also be passed into the `WriteEvent` structure.

The value of the token can be a simple cast from the inner write request pointer.

I can probably come up with a pull request for these tomorrow.

**Comment by nicolasnoble** [comment]
So the real functionality being lost about the write request, is that uvw currently is the sole responsible for managing these resources. This deprives the user of being able to reuse these objets, in case they want to manage them themselves, thus creating unnecessary overhead.

Ultimately, it'd be ideal if the user can:

 - Derive an object from a `uvw::WriteReq`;
 - Optionally pass one of these to any of the `write` calls - if none is provided, then the library should be responsible for creating a generic one and deleting it afterward; and
 - Get the object back into the `WriteEvent` structure.

**Comment by skypjack** [comment]
You can already create requests from a loop actually. Internally, this is what happens.
Also, requests already announce themselves when they _emit_ the `WriteEvent`, similarly to that handles do.
So, if I get it right, all you need is to make requests available rather than an implementation detail, so that you can create them and pass a stream to use to them. Is it?
Wouldn't be enough if `stream<...>::write` returned the `WriteRequest` so that you can also attach your listeners to this one? As far as I can see, you obtain the same result but with less code.

**Comment by skypjack** [comment]
I close this issue because it has been hanging on for too long.
Feel free to reopen it if you want to continue the discussion or propose an alternative solution.
Thank you.
