### ISSUE TITLE
can't generate Doxygen document

### ISSUE THREAD

**Issue by fittachihz** [skypjack/uvw#206]
hi 

Thanks for your great job 

I try to read online docs at [v2.6.0](https://skypjack.github.io/uvw/)
but can't find any useful data there 
it like Doxygen can't find any classes to generate the document

then I try to generate it by my self but after I run CMake 
I get 
`make: *** No rule to make target 'docs'.  Stop.`

so I try to run Doxygen  directly by 
`doxygen docs`
but generated document still same as the online version

**Comment by skypjack** [comment]
You must pass `BUILD_DOC` to cmake to enable the `docs` target.
See [here](https://github.com/skypjack/uvw/blob/master/CMakeLists.txt#L185) for more details.

**Comment by skypjack** [comment]
Updated. I'm pushing on `master` the changes to make it possible to generate the doc locally again.
