### ISSUE TITLE
Added documentation with API reference

### ISSUE THREAD

**Issue by erez-o** [skypjack/uvw#210]
Hi,

I've created a documentation with API reference, you can see an example at https://uvw.docsforge.com/

Hope it's helpful for anyone using UVW. The docs are built automatically every week so they should always be in sync with the code, readme, and any other tutorial files you might add.

If there are any additional tutorial pages you wish to add to the sidebar, or you wish to hide certain internal APIs from being displayed please let me know, everything is configurable.

Disclaimer - I'm the creator of docsforge

**Comment by skypjack** [comment]
Oh... I know you! :smile:

**Comment by skypjack** [comment]
I'm adding you to the list of contributors.
Since I know already how docsforge works, could you add me as a maintainer?
Thanks.

**Comment by erez-o** [comment]
Thanks. 
I transferred ownership.

FYI, you can see a list of all the undocumented API pages in [here](https://uvw.docsforge.com/admin/view-undocumented-pages-log/master/). 
You can go over the list and if anything is important enough, maybe add something.
