### ISSUE TITLE
how can I call tcp.write() with unsigned char

### ISSUE THREAD

**Issue by dreamrover** [skypjack/uvw#211]
Hi,
If I want to send { 0x80, 0x81 }, I can't write as below:
`    tcp->once<uvw::ConnectEvent>([](const uvw::ConnectEvent &, uvw::TCPHandle &tcp) {`
`        auto dataWrite = std::unique_ptr<unsigned char[]>(new unsigned char[2]{ 0x80, 0x81 });`
`        tcp.write(std::move(dataWrite), 2);`
`        tcp.close();`
`    });`

And I didn't find the prototype like:
`write(std::unique_ptr<unsigned char[]> buf, unsigned int len, int64_t offset)`

So is there a way to do this beside this ugly one ?
`unsigned char udata[] = { 0x80, 0x81 };`
`unsigned char *p = udata;`
`tcp.write((char *)p, 2);`

Thanks

**Comment by skypjack** [comment]
It boils down to the fact that `uv_write` in `libuv` works with an `uv_buf_t`. The latter is initialized with `uv_buf_init` and this function accepts only `char *`.
So, you should make this question to the maintainers of `libuv`. `uvw` accepts what can be forwarded to the underlying library to stay true to the `libuv` API.

**Comment by skypjack** [comment]
I'm closing this since your _issue_ is due to the underlying library rather than to `uvw` itself.
Feel free to continue the discussion or to reopen the issue if I didn't answer your question. Thanks.

**Comment by dreamrover** [comment]
Thanks very much.
