### ISSUE TITLE
basehandle::type() in uv_walk which is in a timer callback causes double free

### ISSUE THREAD

**Issue by DuckVador** [skypjack/uvw#212]
![图片](https://user-images.githubusercontent.com/61409963/87410123-7b55c000-c5f8-11ea-8ebb-ef9dddd4f2e9.png)
Code is here: https://pastebin.com/raw/3xeJHfmp
OS: Arch Linux x86_64
Compiler: gcc 10.1.0

**Comment by DuckVador** [comment]
With an interval that is larger than 0ms, the bug is still.

**Comment by stefanofiorentino** [comment]
Cannot reproduce this on Ubuntu 18.04 with Valgrind in Debug Build. 
Neither with 0 and 1000ms repeat.

**Comment by skypjack** [comment]
`h.type()`? I think that's a const function that just returns an integer or such from the underlying library.

**Comment by stefanofiorentino** [comment]
It looks like that:
`Loop::walk` calls `f(ref)` 
which calls `h.type()` 
which calls the `~TimerHandle()`, 
somehow. 
Regreto to say, I cannot currently see the wheres and whys.

**Comment by skypjack** [comment]
:thinking: 
Maybe a copy that shouldn't take place, a missing `&` somewhere. Let me check.

**Comment by stefanofiorentino** [comment]
As far as I can see, I found only `&`s and `*`s.

**Comment by stefanofiorentino** [comment]
Found something, maybe a missing  ```virtual ~BaseHandle() = default;``` solves this issue

**Comment by skypjack** [comment]
Oh. :smile: N00b mistake.

**Comment by stefanofiorentino** [comment]
I'll push tonight.
