### ISSUE TITLE
SSL/TLS support

### ISSUE THREAD

**Issue by bsergean** [skypjack/uvw#229]
Hi there,

Supporting SSL/TLS is pretty essential in my opinion for network code. libuv does not seem to have a strong answer, but the most official thing it seems is the combination of those 2 projects done by a core libuv developer. So maybe they could be wrapped in C++ ? None of those projects are very active which is sad.

* https://github.com/indutny/uv_link_t
* https://github.com/indutny/uv_ssl_t

uv_link_t is also used in this library it seems / https://github.com/aldanor/uv-ssl-client/blob/master/src/client.cpp

In my mind what would be ideal is to have a new object like a uvw::tcp client which is ssl compatible, with the same easy to use apis as the other ones in uvw.

Thoughts ?

**Comment by stefanofiorentino** [comment]
I guess you are talking about a specific ssl frontend, don't you?

**Comment by bsergean** [comment]
That's right there are many ... OpenSSL is the obvious one but there's mbedtls too which is a fine library I've worked with. I used DarwinSSL too (as can be seen in curl), but that one is deprecated now and throw out warnings.

Those other libraries I pointed out use OpenSSL. The one thing annoying with OpenSSL is that it doesn't have proper CMake support yet in the base library (BoringSSL has it though).

**Comment by stefanofiorentino** [comment]
@bsergean, as far as I know, `uvw` will stick with `libuv` implemented behaviors/capabilities. 
I've worked with a (no concurrent) solution, based my experiments on [this](https://github.com/darrenjs/openssl_examples/blob/master/ssl_server_nonblock.c) @darrenjs example.
Hope this helps you.

**Comment by bsergean** [comment]
Thanks for the pointers Stephano. I have written some SSL code myself and it is quite tedious to get things right, which is why I wonder what could be done to hide some of that complexity behind a nice C++ api.

Here is the code I refer too, with 'backends' implementation for OpenSSL, MbedTLS and AppleSSL (which does not really have a name, the best is SecureTransport which is a C api which is deprecated and throw warnings on recent macOS versions).

https://github.com/machinezone/IXWebSocket/blob/master/ixwebsocket/IXSocketAppleSSL.h

For OpenSSL I am not using the BIO interface, this is what the wrapper code looks like. It is not using the concurrent libuv based, the concurrency is thread based in that library. Here is what the code looks like ->

https://github.com/machinezone/IXWebSocket/blob/master/ixwebsocket/IXSocketOpenSSL.cpp

**Comment by skypjack** [comment]
I think we can safely close this issue.
`uvw` sticks with what is offered by `libuv` and SSL isn't part of its API.
So, as far as I can tell, this is something to implement on top of `uvw` as you would implement it on top of `libuv`.
Unfortunately I've not enough bandwidth to implement and maintain a support layer for SSL in my free time. I'm sorry.

**Comment by bsergean** [comment]
That makes sense. Thanks for providing your thoughts !
