### ISSUE TITLE
Shadow warning in fs.h

### ISSUE THREAD

**Issue by stefanofiorentino** [skypjack/uvw#230]
I've just reorganized some warning flags and got this on GCC 7.5.0
```
`uvw/src/uvw/fs.h:359:9: warning: declaration of ‘name’ shadows a member of ‘uvw::FsEvent<(uvw::details::UVFsType)32>’ [-Wshadow]
[build]          : name{name}, type{type}, eos{eos}
```
Same for `type` and `eos`.
I assign it to myself and work on it asap.

**Comment by skypjack** [comment]
Hi @stefanofiorentino any news on this? Can I close the issue?
Even better, if you could share the flags you used, I can look into the warnings and try to fix them on my own.
Thanks.

**Comment by stefanofiorentino** [comment]
I'll close this one as cannot reproduce.
Next time I'll link to the commit and the .vscode/settings
