### ISSUE TITLE
do you try to merge uvw into nodejs source code, and build it?

### ISSUE THREAD

**Issue by anlexN** [skypjack/uvw#232]

**Comment by skypjack** [comment]
Indeed no, it's not exactly something that you merge and try in a few minutes I guess.

**Comment by anlexN** [comment]
@skypjack can you try? it will be amazing. i need uvw to replace libuv in the nodejs?

**Comment by skypjack** [comment]
No, I can't try, definitely. Replacing whatever node.js uses to wrap libuv with uvw is almost certainly a huge work and I don't have enough bandwidth to do that, I'm sorry.

**Comment by anlexN** [comment]
do you know what biggest obstacle is for you? not bandwidth, is youself! i have reviewed nodejs source code, now problem just how to replace libuv. not reinvent something like libuv!
do you know Bruce Lee? he only have 173cm height and 68 kg weight, but he can kick brawny man, far way from around 10 miles. so amazing.
ok, @skypjack , you are good man, i believe you, i also help you review all nodejs source code, that is so easy thing. please believe yourself, go beyond yourself.

**Comment by skypjack** [comment]
🤔 
You reviewed the source code of node.js, you are skilled enough to guide me while replacing their optimized, less general purpose libuv wrapper with uvw and you've apparently no obstacles... You know what? I feel like you could do it! I know you can!
Come on, go beyond yourself and show me that I was wrong! It's something someone can do in a blink, isn't it? So, have a go with it and let me know when you're done! It's 10AM here, what about pinging me before lunch?

**Comment by anlexN** [comment]
1. good man, i have no much time to code in c++ like you. i just know c/c++ syntax that help me understand node source code. 2. i have no experience that develop project like you.
3. i review nodejs source code just because i want to rewrite koajs and i like c++ and javascript.
4. i master javascript better rather than c++.
5. i have read microsoft documents about c/c++ step by step, microsoft embrace c++ but not c. c saytax is implemented a little by them. and microsoft also recommend us to write standard c++.  libuv use windows c exception handling api, it is wrong. because microsoft hope us give up those C exception handling api and recommand us follow standard C++ exception handling. i suggest libuv team rewrite libuv in C++, but they don't want to do it. how unfortunately.
6. i think nodejs just is written by C++ and javascript. our learning time will be decreased much more.

**so i think your success probability is higher than me. if you are willing to wait for me, you will wait me for  more than 1 year.** so long time, don't wait for me.

**Comment by stefanofiorentino** [comment]
As the repo description mentions, `uvw` is an APIs abstraction of libuv, which still does the real stuff under the hood
> Header-only, event based, tiny and easy to use libuv **wrapper** in modern C++ - now available as also shared/static library!

**Comment by skypjack** [comment]
> another idea: first rewrite koajs, then merge uvw into nodejs.

_good man, I don't have much time to program in js like you_.
I also close the issue, since it is completely off topic.
