### ISSUE TITLE
PollHandle's private fd masks Handle's fd()

### ISSUE THREAD

**Issue by jagerman** [skypjack/uvw#236]
`PollHandle` has a private `fd` member, but this masks the base class's `fd()` method, and so the following does not compile:
```C++
#include <uvw.hpp>
#include <iostream>

int main() {
    auto loop = uvw::Loop::getDefault();
    auto poll = loop->resource<uvw::PollHandle>(1);
    std::cerr << poll->fd() << "\n";
}
```
with:
```
foo.cpp:8:24: error: 'fd' is a private member of 'uvw::PollHandle'
    std::cerr << poll->fd() << "\n";
                       ^
src/uvw/poll.h:132:13: note: declared private here
        int fd;
            ^
```
I can still get at with this ugliness:
```C++
    std::cerr << poll->uvw::Handle<uvw::PollHandle, uv_poll_t>::fd() << "\n";
```
but that's gross.

**Comment by skypjack** [comment]
Aha, good catch! 👍 Thanks.

**Comment by skypjack** [comment]
Can I ask you to repeat the test on branch `experimental` before merging into `master`? Thanks.

**Comment by jagerman** [comment]
> Can I ask you to repeat the test on branch `experimental` before merging into `master`? Thanks.

Confirmed, that fixes it.  Thanks!

**Comment by skypjack** [comment]
Great. Thank you for checking it.
