### ISSUE TITLE
Possibly unnecessary std::string copy?

### ISSUE THREAD

**Issue by fireice-uk** [skypjack/uvw#238]
Is this copy necessary (on this and similar functions)? 

https://github.com/skypjack/uvw/blob/58b299ee60d62386a2339dab3f99d30570b33085/src/uvw/tcp.cpp#L46-L52

To my eye `const std::string &` would work just as well

**Comment by stefanofiorentino** [comment]
I guess you are right, in order to evaluate single case, 
would you perchance like to propose a pull request for these (others)?

**Comment by stefanofiorentino** [comment]
@fireice-uk any news about this?

**Comment by fireice-uk** [comment]
I should be able to get some time to do this later this week :)
