### ISSUE TITLE
If send UDP as async, does the uvw will queue message automatically?

### ISSUE THREAD

**Issue by portsip** [skypjack/uvw#251]
If send UDP as async, does the uvw will queued the message automatically?
Can I set the maximum of the queue size?

Thanks

**Comment by skypjack** [comment]
Both questions have nothing to do with `uvw`. The library forwards everything to `libuv` under the hood. Therefore, messages are queued automatically if they are so in `libuv`. Similarly, unless you can set the maximum queue size in `libuv`, you can't do it in `uvw`.
This library stays true to the interface and offer of its underlying library and doesn't add on top of it.

**Comment by skypjack** [comment]
I close this as stale. Feel free to continue the discussion here if you've any doubts. Thanks.
