### ISSUE TITLE
Does uvw is thread-safe?

### ISSUE THREAD

**Issue by pengweichu** [skypjack/uvw#254]
Hello, I'm working on a TCP/UDP client that will send mass messages to the server from numerous threads. Is the uvw thread-safe?

I see the test folder there has an example for AsyncHandle, so if use the TCPHandle rather than AsyncHandle, the uvw will work synchronously?

Thanks

**Comment by skypjack** [comment]
I close this since all questions have been answered and there is nothing to do in `uvw`. 👍
