### ISSUE TITLE
How to handle the data if send fails.

### ISSUE THREAD

**Issue by pengweichu** [skypjack/uvw#255]
If the write is failed, the ErrorEvent will be triggered, but I would like to resend send that data again, so how can get the data in the ErrorEvent?

Can I set any id with the write function then that id will be callback in the ErrorEvent or WriteEvent?

Thanks

**Comment by mutexstream** [comment]
This seems to be a constant pain-point when using this library and it is essentially caused by having all errors published to ErrorEvent. It'd be nice to be able to easily determine the source of an error so the corresponding operation can be retried.

For example, if we had `uvw::WriteErrorEvent`, this write-specific error can contain the data that the user tried to write.

**Comment by skypjack** [comment]
The `v3` branch already contains a lot of changes in this regard.
I'm more than willing to refine it further but please give it a look and try to formulate a request in this regard.

CC @stefanofiorentino side question: what if we merged the branch upstream next week?

**Comment by mutexstream** [comment]
@skypjack Do you have an example of how to perform `write()` retries with the v3 api?

**Comment by mutexstream** [comment]
I ended up modifying the write method in uvw to run a callback in the listener once write completes/fails. The callback then fires whatever events I need to be fired.

**Comment by stefanofiorentino** [comment]
> CC @stefanofiorentino side question: what if we merged the branch upstream next week?

@skypjack up to me it's ok to merge.
Let's remember we'll break several projects pointing to master's HEAD, though.

**Comment by mutexstream** [comment]
For anyone who later stumbles across this issue, here's the modification I made to the `write()` method in the `stream.hpp` file.

```cpp
    void write(char *data, unsigned int len, std::function<void(void)> done) {
        auto req = this->loop().template resource<details::WriteReq>(
                std::unique_ptr < char[], details::WriteReq::Deleter > {
                        data, [](char *) {}
                }, len);

        auto listener = [ptr = this->shared_from_this(), done](const auto &event, const auto &) {
            ptr->publish(event);
            done();
        };

        req->template once<ErrorEvent>(listener);
        req->template once<WriteEvent>(listener);
        req->write(this->template get<uv_stream_t>());
    }
```

Of course, one can have a separate listener for `WriteEvent` and `ErrorEvent` and only run the `done()` callback when a failure occurs (i.e. the `ErrorEvent` listener). The `done()` callback then triggers the retry.

**Comment by mutexstream** [comment]
To spell it all out, the retry logic should look like this.

```cpp
    void write(char *data, unsigned int len, std::function<void(char *data, unsigned int len)> retry) {
        auto req = this->loop().template resource<details::WriteReq>(
                std::unique_ptr < char[], details::WriteReq::Deleter > {
                        data, [](char *) {}
                }, len);

        auto writeListener = [ptr = this->shared_from_this()](const auto &event, const auto &) {
            ptr->publish(event);
        };

        auto errorListener = [ptr = this->shared_from_this(), retry](const auto &event, const auto &) {
            ptr->publish(event);
            retry();
        };

        req->template once<ErrorEvent>(errorListener);
        req->template once<WriteEvent>(writeListener);
        req->write(this->template get<uv_stream_t>());
    }
```
