### ISSUE TITLE
How to handle an existing UNIX socket?

### ISSUE THREAD

**Issue by nmkoremblum** [skypjack/uvw#257]
Hi!

I am trying to handle a UNIX socket (`PipeHandle`) and I noticed that, when using the `bind` method, it creates such a file on the system. Now I am facing the problem that, when the socket already exists on the filesystem, the bind method fails, even though no other process is using it. I've also tried using `connect` but it fails too.

Do you have any advice on how to handle this situation?

Thanks in advance!

**Comment by stefanofiorentino** [comment]
Ciao @nmkoremblum, it is a thing that the application developer should take care of. If the application fails for whatever reason, it's its responsibility to cleanup dangling files. From the other way round, you can always cleanup on startup if you need to (not the best way, but works in many environment). Is it more clear to you now? Do you agree?

**Comment by nmkoremblum** [comment]
Hi @stefanofiorentino! Thanks for answering :smile: 
I was expecting to have a workaround for connecting to an existing socket, of course removing the dangling files came up to my mind, but it seemed to be a naive solution. So, if there is no other way, I will go with that solution.
Thanks again :)

**Comment by skypjack** [comment]
Consider that `uvw` doesn't add anything on top of `libuv`, it's just a wrapper to correctly manage memory automatically.
Therefore, if it's not possible with `libuv`, it's not possible with `uvw`. I guess we're in this case here. 🙂

**Comment by stefanofiorentino** [comment]
Exactly, I'm sure there is a cross-platform way to do it. So no way `libuv` supports it.
I'll close this, feel free to reopen in case you think it needs more discussion.
