### ISSUE TITLE
documentation license is vague

### ISSUE THREAD

**Issue by pemensik** [skypjack/uvw#260]
Readme here documents states documentation is covered by CC BY 4.0. But github repository does not state clearly which files are considered documentation and covered by this license. Repository contains only MIT license file for code.

For a [Fedora package review](https://bugzilla.redhat.com/show_bug.cgi?id=1996325#c2) it is required to specify which files are under which license. Are only files under docs folder considered documentation? Could be CC-BY license text inserted also into repository? Fedora packages demand license text would be shipped together with sources. Unless it should cover only doxygen generated output, it should include also wording of CC-BY 4.0.

It would be nice if more clear license were specified. And it would be best if it specified exactly which files are covered by which license. Can that be improved, please?

**Comment by skypjack** [comment]
Documentation files are generated automatically from the codebase using doxygen, so they don't really exist until you create them. The `docs` dir only contains the cmake file and doxy configuration to generate them.
What would be the right wording for this? The generated files change from time to time or if you use a different version of doxygen, then listing them all wouldn't work.

**Comment by pemensik** [comment]
I am not sure doxygen documentation needs different license than MIT. It is generated from source code, so it should keep original license for it IMHO. GPL would require it as derived code. Any content in addition to just the code is just a tiny part, it is mostly decoration to source code. I think logo is not even present in git itself, only referenced from github site. Ideally each file falling into specific license should have it clearly specified in a comment. For example by https://spdx.org/licenses/ license tag. If doxygen header or footer could be used for generated files, it would make it clear which files fall under that license.

**Comment by skypjack** [comment]
Yeah, I'd rework the license statement and extend the MIT one to the documentation.
I'll push it upstream as soon as possible. Thanks for pointing this out, 👍

**Comment by pemensik** [comment]
No, logo is not a problem, because I haven't found it in git. Therefore it is not present on release archive used to make a package. [Fedora package](https://src.fedoraproject.org/rpms/uvw) is accepted and built. It just needs to clearly define which files are covered by which license. All files in git covered by the single license makes it simpler. I think logo is used only as an image link from README.md. I have found just doxygen generated images in the build and source. I think the change is okay, covering everything required. Thank you.
