### ISSUE TITLE
The library targets are not versioned.

### ISSUE THREAD

**Issue by stefanofiorentino** [skypjack/uvw#268]
Working on the Yocto Project [meta-layer](https://github.com/stefanofiorentino/meta-uvw.git) to natively list `uvw` in the OpenEmbedded Layer index and this [sample application](https://github.com/stefanofiorentino/uvw_static_lib_client.git) (the application delivered by `uvw` inside the test folder, brought in a separated repo), I got the error that the libraries provided (and installed) by this CMake-based project are not versioned (best-practice is that the libuvw.so lib is a symlink to the versioned "concrete" libuvw.so.2.11.2).
I'll work on it.

**Comment by skypjack** [comment]
Cool, **thank you**!! Is it a problem to also port these changes to the `v3` branch? 
From what I see, the `libuv` crew is working on a v2 of the library and I'd like to merge our rework in the meantime.

**Comment by stefanofiorentino** [comment]
Of course yes, let's cherry-pick it once the PR got approved, ok?

**Comment by skypjack** [comment]
Can we close this one? 🤔

**Comment by stefanofiorentino** [comment]
the PR is still not merged (because of 'required' workflows we not support anymore).
I cannot remove this blockers from the settings by myself, sorry for this.

**Comment by skypjack** [comment]
Oho cuz I'm stupid! 😅 
I merged only one of them, sorry. Is it ready?
Also, what about removing the required checks? I want you to be able to proceed on your own, since I trust you 100%.

**Comment by stefanofiorentino** [comment]
I agree with removing the required checks.
The PR is ok to me.

**Comment by skypjack** [comment]
I think you can merge it now? Just to double check that the required checks were turned off. 🙂
