### ISSUE TITLE
Error in .vtu Files with hexahedron type of elements

### ISSUE THREAD

**Issue by nameless2342** [skypjack/uvw#279]
Hello,

I think I found a  small error in the "unstructured.py"-part. The Hexahedron type should only have 8 nodes instead of 9 in the NODES_PER_CELL list. 

CellType.HEXAHEDRON: 8, instead of CellType.HEXAHEDRON: 9, in line 65

(Can lead to problems when you are trying to clip your elements and just added one pseudo node)

Best greetings and thanks - very helpful stuff

**Comment by skypjack** [comment]
I'm pretty sure this isn't the right project.
