### ISSUE TITLE
create v2 branch for bug fixes

### ISSUE THREAD

**Issue by fcelda** [skypjack/uvw#287]
uvw 2.12.1 currently doesn't compile with GCC 13 (Fedora 38) because type_info.hpp doesn't have correct include for standard integers.

```
/home/fcelda/devel/uvw/src/uvw/type_info.hpp:17:37: error: ‘uint32_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
   17 | [[nodiscard]] static constexpr std::uint32_t fnv1a(const char *curr) noexcept {
      |                                     ^~~~~~~~
      |                                     wint_t
```

The fix is trivial, see: https://github.com/skypjack/uvw/compare/v2.12.1_libuv_v1.44...fcelda:uvw:v2?expand=1

Are you planning on maintaining 2.x for a while? I think it would be useful at least for bug fixes.

If so, please, could you create a branch for 2.x? I'm not able to send a PR without it.

Thanks!

**Comment by skypjack** [comment]
> Are you planning on maintaining 2.x for a while?

Define _maintaining_. 🙂 
I'm fine with creating a bug fix branch for the last v2 version, of course.
However, I don't plan to port `uvw` v2 to the new versions of `libuv`, I'm sorry.
I don't have enough bandwidth for that, you know, it's a side open source project after all.

**Comment by skypjack** [comment]
Branch `v2` available upstream. 👍

**Comment by fcelda** [comment]
Thank you!
