### ISSUE TITLE
Q: cpp http server based on libuv

### ISSUE THREAD

**Issue by overthetop** [skypjack/uvw#293]
I'm looking for a fast and an easy to use c++ http server based on libuv. I need to be able to easily register my routes and http handlers. I'll be exposing different http endpoints and use websockets as well. Also Http/websocket client must be present. Can you please tell me if this is possible with uvw or otherwise point me to the right project to use?

**Comment by skypjack** [comment]
`uvw` is just a tiny wrapper around libuv. If it's possible with the latter, it's possible with `uwv`.

**Comment by skypjack** [comment]
No idea, I'm sorry. Especially something in C++ that integrates well with `uvw`.
