### ISSUE TITLE
Issuing multiple filesystem operations at a time with user supplied buffer

### ISSUE THREAD

**Issue by ReimuNotMoe** [skypjack/uvw#309]
If I understand correctly, the `uv_fs_read()` / `uv_fs_write()` can be invoked unlimited times per event loop tick, unlike their socket counterparts.

So is it possible to let the user supply the buffer for `read()`/`write()` in `file_req`  (it's the user's responsibility to manage its lifecycle) ? In this way, multiple requests can be issued sequentially.

**Comment by skypjack** [comment]
Hi, sorry for the late reply.
As far as I can tell, `file_req::write` already accepts an user defined buffer. Am I wrong?

**Comment by skypjack** [comment]
Closing this issue as starving. Feel free to reopen it or continue the discussion here if needed. Thanks.
