### ISSUE TITLE
Question: Pipe process output

### ISSUE THREAD

**Issue by mathisloge** [skypjack/uvw#310]
Take the following code example: 

```cpp
    auto loop = uvw::loop::get_default();
    uvw::process_handle::disable_stdio_inheritance();

    auto process_ = loop->resource<uvw::process_handle>();
    auto out_pipe_ = loop->resource<uvw::pipe_handle>();


    process_->stdio(*out_pipe_,
                    uvw::process_handle::stdio_flags::CREATE_PIPE | uvw::process_handle::stdio_flags::WRITABLE_PIPE |
                        uvw::process_handle::stdio_flags::READABLE_PIPE);
    process_->stdio(uvw::std_in, uvw::process_handle::stdio_flags::IGNORE_STREAM);
    process_->stdio(uvw::std_err, uvw::process_handle::stdio_flags::IGNORE_STREAM);
    (3) process_->stdio(uvw::std_out, uvw::process_handle::stdio_flags::INHERIT_FD);

    out_pipe_->on<uvw::data_event>(
        [](const uvw::data_event &data, const uvw::pipe_handle &pipe) { std::cout << "Got data_event" << std::endl; });
    out_pipe_->on<uvw::listen_event>(
        [](const auto &data, const uvw::pipe_handle &pipe) { std::cout << "Got listen_event" << std::endl; });
    out_pipe_->on<uvw::write_event>(
        [](const auto &data, const uvw::pipe_handle &pipe) { std::cout << "Got write_event" << std::endl; });

    process_->spawn(path_to_application.c_str(), {});
    
```

How to I pipe the stdout into the `out_pipe_`? 
I've tried multiple things, but I got no output from any of the `on` handlers. 
e.g. I've removed `(3)`, tried different flags, alterted the calls of the stdio etc.
The spawned process writes an output every second. With `(3)` and the INHERIT_FD call I get the outputs to my console output. 

Do you know how to do it?

**Comment by skypjack** [comment]
You should direct this question to `libuv` rather than `uwv`, sorry.
This library is just a thin wrapper around the underlying library but doesn't add or change functionality.
Once you know how to do it with `libuv`, I can help you _translate_ it to `uwv` if in troubles. 👍

**Comment by abrownsword** [comment]
I am trying to figure out how to do the same thing as the OP, I think -- i.e. spawn a process that writes back to the parent using a pipe.  Looking at the UVW code, it looks like the ordering of the stdio sources is not preserved, however.  My understanding of the underlying libuv API is that it takes an array of `uv_stdio_container_t` structs and uses them as stdin, stdout, stderr, plus any additional fds to pass to the child.  The problem in UVW is that `stdio(<stream>)` creates one array, and `stdio(<filehandle>)` creates another array, and the former is appended to the latter when building the array to be passed to `uv_spawn`.  This doesn't work if you want to pass `IGNORE` to stdin, and a pipe stream to stdout, and `IGNORE` to stderr.  Instead you'll get `IGNORE` passed to stdin and stdout, and the pipe stream to stderr.

The code in question is in process.cpp `process_handle::spawn`:

```
    std::vector<uv_stdio_container_t> poStdio;
    poStdio.reserve(po_fd_stdio.size() + po_stream_stdio.size());
    poStdio.insert(poStdio.begin(), po_fd_stdio.cbegin(), po_fd_stdio.cend());
    poStdio.insert(poStdio.end(), po_stream_stdio.cbegin(), po_stream_stdio.cend());

    po.stdio_count = static_cast<decltype(po.stdio_count)>(poStdio.size());
    po.stdio = poStdio.data();

```

What I would like to be able to do is essentially (in pseudo-code):

```
    process_handle p;
    p.stdio(std_in, IGNORE_STREAM).stdio(pipe, CREATE_PIPE|WRITEABLE).stdio(std_err, IGNORE_STREAM).spawn(...);
```

Doing that, however, will swap the stdout/stderr.
