### ISSUE TITLE
uvw_net available

### ISSUE THREAD

**Issue by mincequi** [skypjack/uvw#311]
Hi @skypjack,

i don't know if it is worth mentioning (on the uvw repo), but i am working on a small collection of network protocol implementations on top of uvw: https://github.com/mincequi/uvw_net.
Currentkly, i do support http, modbus and sunspec clients, as well as some discoveries, like dns-sd.

Just in case, you are interested...

Cheers

**Comment by skypjack** [comment]
It looks interesting actually. Is it production ready/used somewhere already? Or still under heavy development?
I don't see many tests to be honest. I'd refrain from using it in production without a few of them at least.
Do you plan to add tests and cover the main functionalities before cutting the first _stable_ release?

**Comment by skypjack** [comment]
Gotcha. We can leave the issue open and add a link when a stable release exists then? Makes sense to you?

**Comment by mincequi** [comment]
Hi @skypjack ,
i just created a first release of _uvw_net_ with some unit tests added.

**Comment by skypjack** [comment]
Cool. Do you want to suggest a change to the readme to mention it? I can do it on my own otherwise. I'm not even sure where to put this kind of things yet. Any ideas? 🤔

**Comment by mincequi** [comment]
I will set something up in a few days. Thanks for your offer 👍

**Comment by mincequi** [comment]
Hi @skypjack ,
i finally created a PR that references uvw_net. It took a little more time than expected, because i fixed some bugs and leaks. Now everything seems working stable (in production use already).
Just check my [PR](https://github.com/skypjack/uvw/pull/313) and feel free to edit / find a goot place in your README :)
