### ISSUE TITLE
C++11 / C++14 status?

### ISSUE THREAD

**Issue by breznak** [skypjack/uvw#63]
Great to see this fork is actively developed! :+1: 
Could you please enlighten the C++ standard focus? (11 vs. 14) The `libuv` wiki states it's '14 only, the title here says "modern". Would be great if this could integrate with https://github.com/larroy/uvpp/issues/6 to be its successor.

**Comment by skypjack** [comment]
Focus is on C++14 and the upcoming revision (currently C++1z).
This cannot integrate with uvpp, API and design are completely different, I'm sorry.
I started the project for I didn't like the approaches used so far in the other wrappers.
If you are looking for a drop-in replacement for uvpp, that is not uvw.
