### ISSUE TITLE
Provide doc howto link to custom libuv

### ISSUE THREAD

**Issue by breznak** [skypjack/uvw#65]
Would you consider improving the Readme with a more detailed guide how to link against a custom (built from source, as the newest version is required, #64) `libuv`, please? 

Status: 
- successfully installed `libuv` latest from git to `/usr/local` ; as `>=1.9` is required (#64) 
- older version of libuv is also installed on my system (ubuntu 16.04) as a dependency of other packages
- the `cmake ..` phase fails, due to `libuv` not found:

```
Could NOT find UV (missing: UV_STATIC_LIBRARY UV_SHARED_LIBRARY
  UV_INCLUDE_DIR)
```

**Comment by skypjack** [comment]
If you want to compile the tests and execute them, you *don't have* to compile `libuv` from scratch.
If you read the README file, you'll find that there exists a script named `deps.sh`. Use it.
The _right_ version of `libuv` will be downloaded and compiled for you, as well as `googletest`.
See section *Tests* under *Build Instructions* for further details.

---

On the other side, integrating `uvw` in another project is not something that should be documented in the README file.
As an hint, I'd suggest you to use a `deps.sh` file as `uvw` does. Add `libuv` as a git submodule and copy the `FindUV.cmake` file.
Note that you must be confident with tools like `git` and `cmake` to be able to do that.

**Comment by breznak** [comment]
Sorry for me not RTFM :wink:, running `../deps.sh` indeed solved it! 
I think adding a requirement to CMake for `libuv>=xx and googletest>=xy` might be a cleaner idea, what do you think? And only use/suggest `deps.sh` if those are not already provided on the system.

**Comment by skypjack** [comment]
I think it's worth it keeping under control the versions of the libraries shipped along with `uvw`.
It is also far easier to do with cmake, and this too is a great plus!! :+1:

**Comment by breznak** [comment]
Ok, allow me one last question :) 
All tests compile and pass fine now. 

Problem: linking `uvw` (well, `libuv`) to my custom program.

> Note that libuv is part of the dependencies of the project and it will be cloned by executing the script deps.sh (see below for further details).
Because of that, users have not to install it to compile and execute the tests.

And

> Then pass the proper -I argument to the compiler to add the src directory to the include paths.
Note that users are demanded to correctly setup include directories and libraries search paths for libuv.

So, the `deps` helped me to get the tests passing (dependencies built in `deps/`) but now leave me on my own to build my custom code. 
- Can you add the doc for this section with using the dependencies built in deps/ ?
- or, that's why I've suggested the system-wide requirement of the dependencies above

**Comment by skypjack** [comment]
I've added the system-wide requirements to the README file.
You should not use the dependencies in `deps` in your own project.
How you use `uvw` and how you decide to find and link libraries in your projects doesn't depend on `uvw` and I wouldn't know how to document it.
Anyway, `uvw` is a great source if you want to have an idea on how to proceed, so feel free to look at it and copy whatever you need.
It's an open source project after all. ;-)
