### ISSUE TITLE
buffer management

### ISSUE THREAD

**Issue by kangjoni76** [skypjack/uvw#67]
Thanks Before for wonderful project (y).
Several weeks ago I gave up upon libuv buffer management. I didn't have any idea how to receive clean server data at any size on no matter how much client send. calling uv_read_start requires to call again uv_read_start at the next incoming buffer echo_cb. Say I send 2 mb data post data via curl. how to make uv_read_start friendly by I means without calling uv_read_start again at echo_read_cb. I have set either uv_recv_buffer_size before uv_listen and alloc_cb in uv_read_start to 3mb instead of 65kb yields no effect. Is this case solvable in uvw project?

**Comment by skypjack** [comment]
With `uvw` you can attach your own listener to the `DataEvent` of a socket. It will be invoked each time there are data to be delivered. If you attach also a listener to the `EndEvent` and the other side of the socket closes it once data have been sent, the `EndEvent` will be emitted after all the `DataEvent` and indicates that the communication is over. `uvw` does not alter the behavior of `libuv`. It simply adds a graceful C++ API on top of it.
