### ISSUE TITLE
ProcessHandle::stdio() stream.get() is protected

### ISSUE THREAD

**Issue by raoulh** [skypjack/uvw#81]
I'm trying to use uvw::ProcessHandle::stdio() and it does not build when doing:
```
auto pipe = loop.resource<uvw::PipeHandle>();
exeCurl->stdio(flags, *pipe);
```
The build failed with an error caused by get() being protected:
```
container.data.stream = stream.template get<uv_stream_t>();
```
https://github.com/skypjack/uvw/blob/master/src/uvw/process.hpp#L213

**Comment by skypjack** [comment]
See [b54d753](https://github.com/skypjack/uvw/commit/b54d7537d185cfca23aec95710c4533203ce0768).
