### ISSUE TITLE
Expose type in BaseHandle

### ISSUE THREAD

**Issue by bmagistro** [skypjack/uvw#99]
From the libuv docs it appears that uv_handle_t has the ability to provide the type.  It would be nice if this was also available in uvw.   Per docs calling loop->walk on the thread's loop only provides the count and cannot get you back to the handle type.

Use case:
We would like to report periodic stats on the number of open/active handles in a thread grouped by type.  

Edit:
Co worker suggested using typeid() which does seem to allow me to get back to the type.

**Comment by skypjack** [comment]
I don't get it. You want the underlying type exposed (ie `uv_tcp_t`) or the lib type (ie `TcpHandle`)?
`typeid` smells more of a workaround than of a solution.

**Comment by skypjack** [comment]
Ok, nevermind. I've just figured out how to implement it. It shouldn't be much difficult. I hope I can put it upstream as soon as possible.

I'll add a new opaque member function to `BaseHandle`, so that you can use it while walking through the list of active handles. Return type will be `HandleType` as defined in `util.hpp`.
Is it fine for you? That's the best we can get out of it currently.

**Comment by skypjack** [comment]
Upstream. See [this](https://github.com/skypjack/uvw/commit/cf14a05eb0425fb6c1fca1c16bfa65137e61ff4c) commit for more details.
I've also updated the documentation.

**Comment by bmagistro** [comment]
Docs wise I was looking at http://docs.libuv.org/en/v1.x/handle.html from libuv, specifically member variables.

I would agree `typeid` is a bit of a workaround.  As for the type, I am not sure I have a preference between lib type (`TcpHandle`, `TimerHandle`, etc) or the underlying type `uv_tcp_t`.  I would probably opt easier first and then prefer lib type so that it is consistent within uvw.

Looking at the commits I think that will allow us to get the info we are after.  Many thanks!

**Comment by skypjack** [comment]
Library type is already available. Hope it helps you.

Just out of curiosity, can I ask you for what you are using `uvw`?  
If you are interested in this kind of things, there is also a section in the readme dedicated to the projects that use this library.
